### ISSUE TITLE
Make /etc/init.d/flowvisor more configurable

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#10]
Status: Open
Project:    Flowvisor
Component/s:     None
Affects Version/s:   None
Fix Version/s:   None

Type:    Bug    Priority:    Major
Reporter:   Josh Smift  Assignee:   Ali Al-Shabibi
Resolution:  Unresolved Votes:   0
Labels:  willfix
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
Put anything that you want to be a user-settable variable into a config file that /etc/init.d can read, like /etc/default/flowvisor on Ubuntu (and, I think, other Debian-like systems), /etc/sysconfig/flowvisor on Red Hat (and derivatives), etc, so you can change FV_USER and FV_CONFIG, without modifying /etc/init.d.

 Comments  
Comment by Josh Smift [ 28/Aug/12 ]
We talked about this on IRC, and concluded that we liked the idea of having the package create the user that it wants to run as (FLOWVISOR-149), in which case that doesn't really need to be configurable (because it's no longer the responsibility of the admin to create a user); and FV_CONFIG is gone anyway, now that config info is in a DB. So, I think this ticket can be closed as wontfix (or whatever the appropriate JIRA thing is).

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-148

**Comment by jbsbbn** [comment]
I'd commented, on the JIRA predecessor to this ticket, that I think this issue has been addressed in different ways, and that this one can be closed; I still think that.
