### ISSUE TITLE
Missing instructions for package install

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#11]
Status: Open
Project:    Flowvisor
Component/s:    Packaging
Affects Version/s:  0.8.1
Fix Version/s:   None

Type:    Bug    Priority:    Major
Reporter:   Luisa Nevers    Assignee:   Nick Bastin
Resolution:  Unresolved Votes:   0
Labels:  None
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified
Environment:  
Ubuntu 10.04.2 LTS
Ubuntu package FlowVisor 0.8.1.2

 Description  
Using instructions from https://openflow.stanford.edu/display/flowvisor/fv_deploy.
If a user follow the "install ubuntu package and configure" path there are two issues:
the instructions jump into using a password, but no instructions are given to set/generate
a FlowVisor password.
Also missing are instructions to set the user/group for the FlowVisor.

 Comments  
Comment by Josh Smift [ 29/Aug/12 ]
The page that this ticket is about, it no longer exists. The new page has some issues, but I think this particular ticket can be closed.

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-137

**Comment by alshabib** [comment]
Closing because install process has changed and it is documented in the wiki
