### ISSUE TITLE
Path and naming mismatches between FlowVisor package and documentation

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#12]
Status: Open
Project:    Flowvisor
Component/s:    Packaging
Affects Version/s:  0.8.1
Fix Version/s:   None

Type:    Bug    Priority:    Minor
Reporter:   Luisa Nevers    Assignee:   Nick Bastin
Resolution:  Unresolved Votes:   0
Labels:  None
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified
Environment:  
OS Ubuntu 10.04.2 LTS
Ubuntu package FlowVisor 0.8.1.2

 Description  
Followed the instructions for a FlowVisor Ubuntu package install and 
configuration on a new system and have run into path and naming issues.
The page https://openflow.stanford.edu/display/flowvisor/fv_deploy points to a 
file /usr/local/etc/flowvisor/flowvisor-config.xml, but file that is delivered 
by the package has different name and exists in a different path 
/usr/etc/flowvisor/config.xml.
Additionally, there are several mismatched paths in the fv_deploy page and the installed package:
doc=> /usr/local/sbin/ package installs=> /usr/sbin/
doc=> /usr/local/etc/flowvisor/ package installs=> /usr/etc/flowvisor/
Package-installation specific steps should use path and naming that is delivered.

 Comments  
Comment by Luisa Nevers [ 28/Sep/11 ]
A comment about the path mismatch and the configuration naming consistency, as delivered by the package the "/etc/init.d/flowvisor" will not work because it executes the following command:
sudo -u flowvisor /usr/sbin/flowvisor /usr/etc/flowvisor/config.xml
The user "flowvisor" does not exist, the configuration "config.xml is a sample configuration and the documentation instruct the user to generate their own with a different file name "flowvisor-config.xml" without instruction to modify the system start-up file.
Comment by Josh Smift [ 29/Aug/12 ]
The page that this ticket is about, it no longer exists. The new page has some issues, but I think this particular ticket can be closed.

original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-136

**Comment by alshabib** [comment]
closing because this refers to the replaced xml configuration backend
