### ISSUE TITLE
Rotate /var/log/flowvisor/flowvisor-stderr.log

### ISSUE THREAD

**Issue by jbsbbn** [opennetworkinglab/flowvisor#128]
/etc/init.d/flowvisor writes to /var/log/flowvisor/flowvisor-stderr.log, but nothing ever rotates this file; something should. (Perhaps the init.d script itself -- maybe check at startup to see if the file is larger than a certain size, and if it is, rotate it and compress it?)

**Comment by nbastin** [comment]
The package should add a config to /etc/logrotate.d/ that handles the flowvisor logs.  Keep in mind this is a packaging problem - every distribution does this differently so it needs to be something in the package rather than in the software itself.

**Comment by jbsbbn** [comment]
I disagree that this should be done by logrotate, because that means FlowVisor will restart whenever logrotate runs, which I think is highly undesirable.

I think this should be done in the init script at start time, when you already know that FlowVisor isn't running.

**Comment by nbastin** [comment]
I'm not sure why you believe that FlowVisor would restart.  Logrotate doesn't do _anything_ inherently that would cause FV to restart.  If the packager made the decision to restart FV in the 'postrotate' step, yes, that would be ill-advised.  I would think the logrotate conf would look something like:

```
/var/log/flowvisor/flowvisor-stderr.log {
   size 1M
   copytruncate
   rotate 10
   compress
   maxage 100
   missingok
}
```

Or at least that's what it looks like on my system.

**Comment by jbsbbn** [comment]
What causes FV to stop writing to the old file, and start writing to the new one?

**Comment by nbastin** [comment]
Nothing, that's what copytruncate is for - it supports apps that don't like their file handle being changed underneath them.  Instead it copies the file to rotate it, and then truncates the original to zero length, so FV keeps writing the same file forever.  It's possible to lose a small amount of data this way, but I don't think that's a big deal in this case.

**Comment by jbsbbn** [comment]
Ah, ok, in that case it should be fine then.
