### ISSUE TITLE
FlowVisor no longer detects duplicate controllers

### ISSUE THREAD

**Issue by jbsbbn** [opennetworkinglab/flowvisor#135]
In FV 0.8.13, if I create a slice that uses the same controller as an existing slice, it succeeds; this used to fail.

**Comment by jbsbbn** [comment]
For example:

```
[14:23:46] jbs@smyrna:/home/jbs
+$ fvctl --passwd-file=/etc/flowvisor/fvpasswd getSliceInfo 34d126b1-40f6-4af5-aa23-b414ca691be2 | grep controller
controller_port=9933
controller_hostname=flowvisor.gpolab.bbn.com

[14:23:50] jbs@smyrna:/home/jbs
+$ fvctl --passwd-file=/etc/flowvisor/fvpasswd createSlice test tcp:flowvisor.gpolab.bbn.com:9933 jbs@bbn.com
New password: 
success!
```

I'm pretty sure this used to fail; did it change deliberately?

**Comment by alshabib** [comment]
I feel like this has been discussed and we decided to remove this
restriction and trust admins to know what they are doing.

## 

Ali Al-Shabibi (sent from handheld)

On 5 déc. 2012, at 20:26, Josh Smift notifications@github.com wrote:

For example:

[14:23:46] jbs@smyrna:/home/jbs
+$ fvctl --passwd-file=/etc/flowvisor/fvpasswd getSliceInfo
34d126b1-40f6-4af5-aa23-b414ca691be2 | grep controller
controller_port=9933
controller_hostname=flowvisor.gpolab.bbn.com

[14:23:50] jbs@smyrna:/home/jbs
+$ fvctl --passwd-file=/etc/flowvisor/fvpasswd createSlice test
tcp:flowvisor.gpolab.bbn.com:9933 jbs@bbn.com
New password:
success!

I'm pretty sure this used to fail; did it change deliberately?

—
Reply to this email directly or view it on
GitHubhttps://github.com/OPENNETWORKINGLAB/flowvisor/issues/135#issuecomment-11056301.

**Comment by jbsbbn** [comment]
Hmm, well, it's a big problem for FOAM, which can auto-approve a sliver, and thus create an FV slice, without an admin (who may or may not know what they're doing :^) having anything to do with it.

**Comment by alshabib** [comment]
Ok well I am sure this was discussed with nbastin at the time. I'd have to
double check. It's no big problem for me either way, it's a quick fix.

## 

Ali Al-Shabibi (sent from handheld)

On 5 déc. 2012, at 20:38, Josh Smift notifications@github.com wrote:

Hmm, well, it's a big problem for FOAM, which can auto-approve a sliver,
and thus create an FV slice, without an admin (who may or may not know what
they're doing :^) having anything to do with it.

—
Reply to this email directly or view it on
GitHubhttps://github.com/OPENNETWORKINGLAB/flowvisor/issues/135#issuecomment-11056862.

**Comment by nbastin** [comment]
I do believe this should be allowed, but I also believe that the check should be configurable (because GENI wants it on, for example).  However, that being said, it was never explicitly removed - there's actually code in FV that believes it is checking this, it just doesn't work:

in SliceImpl.java:

``` java
48    private static String CONTCHECK = "SELECT id from Slice WHERE " + HOST + " = ? AND " + PORT + " = ?"; 
.....
529         ps = conn.prepareStatement(CONTCHECK);
530         ps.setString(1, controller_hostname);
531         ps.setInt(2, controller_port);
532         if (!ps.execute())
533             throw new DuplicateControllerException(controller_hostname, controller_port, sliceName, null);
```

The problem is that returning a row isn't an execution failure, so this check will never fail unless there's an internal database error.
