### ISSUE TITLE
error about message ECHO_REQUEST

### ISSUE THREAD

**Issue by caiqs-sys** [opennetworkinglab/flowvisor#146]
The error information looks like the following
DEBUG:2012-12-17T11:18:10.714:classifier-dpid=00:00:7a:48:2b:c0:28:40:: received from switch: ofmsg:v=1;t=ECHO_REQUEST;l=8;x=0
DEBUG:2012-12-17T11:18:10.714:classifier-dpid=00:00:7a:48:2b:c0:28:40:: send to switch:ofmsg:v=1;t=ECHO_REPLY;l=8;x=0
DEBUG:2012-12-17T11:18:10.823:classifier-dpid=00:00:7a:48:2b:c0:28:40:: send to switch:ofmsg:v=1;t=ECHO_REQUEST;l=0;x=100
 CRIT:2012-12-17T11:18:10.823:none:: dropping bad OF Message: ofmsg:v=1;t=ECHO_REQUEST;l=8;x=100
org.flowvisor.exceptions.MalformedOFMessage: len=0,wrote=8 msg=ofmsg:v=1;t=ECHO_REQUEST;l=8;x=100
    at org.flowvisor.io.FVMessageAsyncStream.testAndWrite(FVMessageAsyncStream.java:79)
    at org.flowvisor.classifier.FVClassifier.sendMsg(FVClassifier.java:687)
    at org.flowvisor.events.OFKeepAlive.sendPing(OFKeepAlive.java:70)
    at org.flowvisor.classifier.FVClassifier.handleKeepAlive(FVClassifier.java:367)
    at org.flowvisor.classifier.FVClassifier.handleEvent(FVClassifier.java:342)
    at org.flowvisor.fvtimer.FVTimer.processEvent(FVTimer.java:64)
    at org.flowvisor.events.FVEventLoop.doEventLoop(FVEventLoop.java:131)
    at org.flowvisor.FlowVisor.run(FlowVisor.java:196)
    at org.flowvisor.FlowVisor.main(FlowVisor.java:229)
 CRIT:2012-12-17T11:18:10.823:classifier-dpid=00:00:7a:48:2b:c0:28:40:: BUG: bad msg: org.flowvisor.exceptions.MalformedOFMessage: len=0,wrote=8 msg=ofmsg:v=1;t=ECHO_REQUEST;l=8;x=100
DEBUG:2012-12-17T11:18:11.119:slicer_xiaocai_dpid=00:00:7a:48:2b:c0:28:40:: send to controller: ofmsg:v=1;t=ECHO_REQUEST;l=0;x=100
 CRIT:2012-12-17T11:18:11.119:none:: dropping bad OF Message: ofmsg:v=1;t=ECHO_REQUEST;l=8;x=100
 CRIT:2012-12-17T11:18:11.119:slicer_xiaocai_dpid=00:00:7a:48:2b:c0:28:40:: BUG: org.flowvisor.exceptions.MalformedOFMessage: len=0,wrote=8 msg=ofmsg:v=1;t=ECHO_REQUEST;l=8;x=100

**Comment by alshabib** [comment]
Could you tell me which version of flowvisor you are running and are their any particular conditions under which this happens?

**Comment by caiqs-sys** [comment]
Thanks for your reply alshabib.
I obtain the source code through "git clone git clone http://github.com/OPENNETWORKINGLAB/flowvisor.git", then choose File->new project->Java Project from Existing Ant Buildfile, then run FlowVisor.java with the following VM Arguments:
-Dorg.flowvisor.config_dir=/etc/flowvisor
-Dorg.flowvisor.install_dir=/usr/local/libexec/flowvisor
-Dderby.system.home=/usr/local/share/db/flowvisor
-Dfvlog.configuration=/etc/flowvisor/fvlog.config
-Djavax.net.ssl.keyStore=/etc/flowvisor/mySSLKeyStore 
-Djavax.net.ssl.keyStorePassword=CHANGEME_PASSWD
with Program arguments: -d DEBUG -l

Besides, I create a ovs bridge and use ovs-ovsctl set-controller to connect it to flowvisor
I also create a slice called xiaocai, it looks like this:
flowvisor@ubuntu-compute-4:/root$ fvctl getSliceInfo xiaocai
Enter fvadmin's passwd: 
Got reply:
drop_policy=exact
connection_1=00:00:7a:48:2b:c0:28:40-->/10.107.219.56:48765-->/10.107.219.65:6633
contact_email=xiaocai@email.com
controller_hostname=10.107.219.65
controller_port=6633
creator=fvadmin

flowvisor@ubuntu-compute-4:/root$ fvctl getSliceStats xiaocai
Enter fvadmin's passwd: 
Got reply:
---Sent---
slicer_xiaocai_dpid=00:00:7a:48:2b:c0:28:40 :: ECHO_REQUEST=3,ECHO_REPLY=1,STATS_REPLY.DESC=2,FLOW_MOD=2,FEATURES_REQUEST=2,STATS_REQUEST.DESC=2,GET_CONFIG_REQUEST=2,FEATURES_REPLY=2,GET_CONFIG_REPLY=2,HELLO=4,SET_CONFIG=2
Total :: ECHO_REQUEST=3,ECHO_REPLY=1,STATS_REPLY.DESC=2,FLOW_MOD=2,FEATURES_REQUEST=2,STATS_REQUEST.DESC=2,GET_CONFIG_REQUEST=2,FEATURES_REPLY=2,GET_CONFIG_REPLY=2,HELLO=4,SET_CONFIG=2
---Recv---
slicer_xiaocai_dpid=00:00:7a:48:2b:c0:28:40 :: ECHO_REQUEST=1,FLOW_MOD=2,FEATURES_REQUEST=2,STATS_REQUEST.DESC=2,GET_CONFIG_REQUEST=2,HELLO=2,SET_CONFIG=2
Total :: ECHO_REQUEST=1,FLOW_MOD=2,FEATURES_REQUEST=2,STATS_REQUEST.DESC=2,GET_CONFIG_REQUEST=2,HELLO=2,SET_CONFIG=2
---Drop---
slicer_xiaocai_dpid=00:00:7a:48:2b:c0:28:40 :: ECHO_REQUEST=2
Total :: ECHO_REQUEST=2

**Comment by alshabib** [comment]
openflowj stopped setting lengths by default. fix is now applied.
