### ISSUE TITLE
LLDP packet made by FlowVisor doesn't have "the end of LLDPDU" nor a TLV header before padding(0xcafebabe)

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#15]
Status: Open
Project:    Flowvisor
Component/s:    Core
Affects Version/s:  0.8.1
Fix Version/s:   None

Type:    Bug    Priority:    Minor
Reporter:   Masahiko Takahashi  Assignee:   Nick Bastin
Resolution:  Unresolved Votes:   0
Labels:  Flowvisor, NEC
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

Attachments:     Add-the-end-of-LLDPDU.patch    

 Description  
When looking at packet dump with wireshark, LLDP packets made and sent by FlowVisor
were marked as "malformed packet." Because an LLDP packet made by FlowVisor doesn't
have "the end of LLDPDU" nor a TLV header, but followed by padding(0xcafebabe) that
is recognized as "type = 101, length = 254"(shown by wireshark). The attached patch
inserts "the end of LLDPDU" and proper TLV header for the padding. In addition, it
modifies some other things regarding LLDP packet, which are not big deals, though.

 Comments  
Comment by Ali Al-Shabibi [ 06/Feb/12 ]
missing patch....
Comment by Masahiko Takahashi [ 07/Feb/12 ]
Here is a patch...
From 79005596f4bc637dab77ddf518819cf37758f938 Mon Sep 17 00:00:00 2001
From: Masahiko Takahashi masahik7@stanford.edu
Date: Fri, 2 Sep 2011 15:48:24 -0700
Subject: [PATCH] LLDP: Adding "the end of LLDPDU" and proper TLV header before padding.

An LLDP packet made and sent by FlowVisor has no "the of of LLDPDU"
(0x00, 0x00) before padding (0xcafebabe), which results in improper
type and length as TLV header. This patch inserts "the end of LLDPDU"
## and proper TLV header for the padding.

 src/org/flowvisor/message/lldp/LLDPTrailer.java    |    2 +-
 src/org/flowvisor/ofswitch/TopologyConnection.java |   12 +++++++++++-
 2 files changed, 12 insertions(+), 2 deletions(-)

diff --git a/src/org/flowvisor/message/lldp/LLDPTrailer.java b/src/org/flowvisor/message/lldp/LLDPTrailer.java
index c020ea7..3938183 100644
--- a/src/org/flowvisor/message/lldp/LLDPTrailer.java
+++ b/src/org/flowvisor/message/lldp/LLDPTrailer.java
@@ -87,7 +87,7 @@ public class LLDPTrailer {
        ByteBuffer newPacket = ByteBuffer.allocate(embedded.length + len);
        newPacket.put(embedded);
-       int tlv = (len & 0x1ff) | ((LLDP_CHASSIS_ID & 0x007f) << 9);
- ```
    int tlv = ((len - TLV_LEN) & 0x1ff) | ((LLDP_CHASSIS_ID & 0x007f) << 9);
  newPacket.putShort((short) tlv);
  
  newPacket.put(LLDP_CHASSIS_ID_LOCAL);
  ```
  
  diff --git a/src/org/flowvisor/ofswitch/TopologyConnection.java b/src/org/flowvisor/ofswitch/TopologyConnection.java
  index 66ecc29..5e0ddff 100644
  --- a/src/org/flowvisor/ofswitch/TopologyConnection.java
  +++ b/src/org/flowvisor/ofswitch/TopologyConnection.java
  @@ -482,13 +482,23 @@ public class TopologyConnection implements FVEventHandler, FVSendMsg {
      bb.putShort(portNumber);
  
  ```
  // TTL TLV
  ```
-       byte ttl[] = { 0x06, 0x02, 0x00, 0x70 };
- ```
    byte ttl[] = { 0x06, 0x02, 0x00, 0x78 };
  bb.put(ttl); // type 3, length 2, 120 seconds
  
  // SysD TLV
  bb.put(lldpSysD);
  bb.putLong(this.featuresReply.getDatapathId());
  ```
- ```
    // End of LLDPDU
  ```
-       byte endoflldp[] = { 0x00, 0x00 };
-       bb.put(endoflldp); // type 0, length 0
  +
-       // padding
-       if (bb.position() > (size - 4))
-           return buf;
-       int tlv = ((size - bb.position() - 2) & 0x1ff) | ((1 & 0x007f) << 9); // LLDP_CHAEEIS_ID << 9
-       bb.putShort((short) tlv);
-       bb.put((byte) 0x07); // subtype = LLDP_CHASSIS_ID_LOCAL
      while (bb.position() <= (size - 4))
          bb.putInt(0xcafebabe); // fill with well known padding
      return buf;
  -- 
  1.7.0.4

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-131

**Comment by mssumanth** [comment]
Fixed in 1.2
Committed in: 6685bf82d59abf09fa1b80f23509ac8d5d7849ed
Instead of adding a custom-made trailer, we add the slice-name and flowvisor name information
in the optional Organizational TLV information field and append the entire LLDP trailer in a standard
way with the OUI ID of ON.Labs = 0xa42305 and the subtype = 0x01
