### ISSUE TITLE
JSON API for get-version

### ISSUE THREAD

**Issue by nbastin** [opennetworkinglab/flowvisor#151]
Right now you can (somewhat obtusely) use xmlrpc ping to determine the version, but if someone disables the XML-RPC API there's no way to get this information (and thus will be no way to get it when the XML-RPC API goes away completely).

**Comment by alshabib** [comment]
Implemented in nightly. The JSONRPC is still disabled by default, but when 1.0 is released the JSONRPC will be active and the XMLRPC will be deprecated.
