### ISSUE TITLE
Control planes with multiple flowvisors should not broadcast LLDP packet-ins to all slices

### ISSUE THREAD

**Issue by gth828r** [opennetworkinglab/flowvisor#158]
In setups where there are multiple flowvisors on a given control plane, the slicing of LLDP traffic is somewhat messy.  
Below is an example topology:
![stacked_fv_lldp_issue](https://f.cloud.github.com/assets/385222/36680/a06fbee0-535f-11e2-8ca7-77cb11a22836.png)

Consider the following example scenario:
- Controller A sends OFP+LLDP packet-out to top tier FV
- Upper-tier FV marks OFP+LLDP as associated with controller A, sends OFP+LLDP packet-out to lower-tier FV
- Lower-tier FV tries to mark OFP+LLDP as associated with upper-tier FV, but fails, then sends OFP+LLDP packet-out to switch
- LLDP traverses data plane, hits connected switches
- All connected switches generate OFP+LLDP packet-ins and send them to the lower tier FV
- Lower-tier FV can't tell which slice to send the OFP+LLDP packet-ins to, so it sends them to all of the upstream controllers (in this case, controllers B through Z)

The number of OFP+LLDP packet-ins on the control plane can grow very quickly.  This might be a minor annoyance when monitoring control plane traffic, but if the amount of LLDP scales too high, it can disrupt real control plane traffic.

**Comment by alshabib** [comment]
Have you tried setting the lldp_spam parameter to false for slices which should not receive unknown lldp packets? This may be a sufficient workaround for your situation. The lldp_spam option can be configured in the config file for each slice.

**Comment by gth828r** [comment]
We chatted about this for a bit, and we determined that the lldp_spam option does help with the upstream flowvisor issue, but it causes problems for incoming LLDP packets from neighboring OF networks that are controlled by flowvisor (what Nick has been calling the "peer flowvisor" problem.  In GENI, federated flowvisors currently use different Flowvisor slice names for traffic that belongs in the same GENI slice.  When an LLDP packet leaves the data plane of one network and enters another, if the lldp_spam option was enabled, then the no packet-in would be sent to the upstream controller.

So when solving this problem, there are two things to consider:
- Upstream flowvisors (as pictured in the issue description)
- Peer flowvisors for federated networks

It was mentioned that part of this issue could be resolved as part of a fix for  https://github.com/OPENNETWORKINGLAB/flowvisor/issues/142.

**Comment by alshabib** [comment]
Could someone remind me why we think that if the lldp_spam option is enabled we would not see the LLDP at the controller when the LLDP comes from another federate? 

In particular, I don't actually believe that the below statement is true?

"When an LLDP packet leaves the data plane of one network and enters another, if the lldp_spam option was enabled, then the no packet-in would be sent to the upstream controller."

 Has anyone actually tried this?

**Comment by gth828r** [comment]
Were you thinking of a case where the FVs might have the exact same FV slice name, or are you thinking of something more generic?

Assuming the former, I think the problem is that within a GENI slice, flowvisor slice names in the federated flowvisors are not the same.  Its been a while since we talked about this, but IIRC, flowvisor marks the LLDP traffic with the FV slice name to determine which slice given LLDP traffic belongs to when enabling the lldp_spam option.

If two federated flowvisors (fv1 and fv2) both had FV slices within a GENI slice tuptyslice, fv1 would mark the LLDP traffic with its version of the slice name (tuptyslice-blah1),  but once the packet-in for that LLDP traffic arrived at fv2, the marked slice name would not match anything that fv2 knows about.

**Comment by alshabib** [comment]
I was actually referring to case of the peer flowvisor problem. 

So when a slice is opted in for lldp spam, the controller will receive the the lldp packet as long as it's controller is up and the port the lldp was received on is part of the slice. This, of course, may cause your peer fv to broadcast the packet to all slice controller it has set up. Does someone have a setup where they can quickly test this? If not, I can probably set something up in our lab that would be similar.

A simple solution to this problem, would probably be to have federated geni slices to have the same slice name at every federate. But I realize that this is opening a whole other can of worms.

**Comment by gth828r** [comment]
I chatted with Nick briefly... I guess if you think purely about the peer fv problem, then using the same slice name at every FV might work, but I think there are some problems:
- The Slice URN might be too long to fit into the existing way that FV encodes slices into LLDP
- FOAM currently uses UUIDs that correspond to GENI slivers (and not GENI slices) to name FV slices, so that would have to change

I think we should probably open a separate ticket for the peer flowvisor problem, because it is pretty much tangential to this one.  I am mixing things up in my brain. :)

Also, I think you DO still have to deal with the case where you have multiple tiers of FVs, and the lower-tier FVs are peers.  In that case, doesn't the lower tier FV currently have problems writing the slice name into the LLDP packets, because the upper-tier FV already wrote into the packet?  Anyway, I think that solution comes for free if you solve both the stacked FV problem and the peer FV problem.

**Comment by alshabib** [comment]
We definitely have to fix the way we construct LLDP packets for mainly two reasons:
1. Writing stuff in the trailer is completely non standard.
2. We need to support stacked FVs.

So if we at least use TLVs to store slice names, that'll solve the stacked FV issue. Since we can append slice names to the TLV (up to some limit) or use a separate TLV per flowvisor but that may require to introduce a notion of FV rank to know which TLV is for which FV. That said, I still think slice names should be the same for a slice which is federated, but I do realise this means a change at FOAM. So starting a separate issue for peer-fvs is a good idea. Could someone open  that ticket?

**Comment by mssumanth** [comment]
Fixed the way we construct LLDPs 
by constructing them in a standard IEEE specified way
in 1.2 with the commit: 6685bf82d59abf09fa1b80f23509ac8d5d7849ed
