### ISSUE TITLE
Make it possible for normal users to add labels to tickets

### ISSUE THREAD

**Issue by jbsbbn** [opennetworkinglab/flowvisor#162]
When I created a new ticket just now, I didn't see any way to add a label to it. Can ordinary users do this? If not, please enable it. (If so, please document it. :^)

**Comment by alshabib** [comment]
This is currently impossible with the github tracker. Only way is to give 'normal users' push permissions. For now, I will label your issues. Until we make a move back to jira.

**Comment by jbsbbn** [comment]
AA> This is currently impossible with the github tracker. Only way is to
AA> give 'normal users' push permissions. For now, I will label your
AA> issues. Until we make a move back to jira.

All righty; I'll rustle up a list and send it your way, maybe today, if
not then Monday.

```
                                  -Josh (jbs@bbn.com)
```

**Comment by alshabib** [comment]
Unfortunately, this is not possible unless we make a GPO member part of the FlowVisor github project. Github's workflow is that only maintainer should be able to classify bugs.
