### ISSUE TITLE
Log level of packets not matching any slice in Flowvisor

### ISSUE THREAD

**Issue by innnkkki** [opennetworkinglab/flowvisor#187]
RIght now it is WARN, but this is too high for this event.

**Comment by mssumanth** [comment]
This is fixed but not merged into the 1.0 release, will be added in the later versions. Currently without the fix, the log level is taken from different places like : the fvlog.config or config.json or the level specified through the command line.

**Comment by alshabib** [comment]
The issue here is to change the default loglevel to WARN and set the log statement for the 'no match' in FlowSpaceRuleStore:663 to INFO
