### ISSUE TITLE
How can we create a slice that have min-rate queue?

### ISSUE THREAD

**Issue by lionelli1** [opennetworkinglab/flowvisor#190]
Is there an easy way to specify the min-rate for each slice?

From what I know we can create min-rate queues to a switch by using dpctl add-queue, but I was wondering if there is any easier way to impose a minimum bandwidth on a slice on the FlowVisor slice level. Thanks!

**Comment by alshabib** [comment]
FlowVisor assumes that queues have already been provisioned out of band. Therefore, you must create them first and then pass the queue ids to FlowVisor. If you can think of a better way to do it, I am open to suggestions/contributions.

Again, please ask questions on the openflow-discuss mailing list.
