### ISSUE TITLE
improve error reporting when FV is not running

### ISSUE THREAD

**Issue by brandonheller** [opennetworkinglab/flowvisor#195]
If you restart FV and then go to run fvctl, you see this:

```
mininet@mininet:~$ fvctl -f /dev/null get-config
Traceback (most recent call last):
  File "/usr/bin/fvctl", line 982, in <module>
    do_func(gopts, opts, args)
  File "/usr/bin/fvctl", line 423, in do_getConfig
    ret = connect(gopts, "get-config", passwd, data=req)
  File "/usr/bin/fvctl", line 706, in connect
    ph = opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1219, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1181, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
```

How about catching the error and exiting with:

```
Could not reach a FlowVisor RPC server at localhost:8080. 
Please check that FlowVisor is running and try again.
```

**Comment by brandonheller** [comment]
Was this fixed with a commit, or marked as won't-fix?

**Comment by alshabib** [comment]
fixed in 1.0.2

**Comment by brandonheller** [comment]
Do you see why such messages are frustrating?  

You're pushing the work of figuring out where this change was made, and how it was made, to anyone who wants to see what error message to expect in the future.  Sure, I _could_ launch an FV environment, upgrade the version (which for all I know may require a source install), and run through a test script, just to get this simple answer. 

Or, you could simply reference the commit, and make it easy for me and anyone else who is completely unfamiliar with the code to know what error message to expect.  C'mon man...

**Comment by alshabib** [comment]
Thanks Brandon. The fact that we don't use the same development model as you do shouldn't be such an issue for you. FlowVisor user are used to pick up the latest versions, either by source or binary. Anyway, point taken, I will reference commits in the future. The commit for this one is 446d926287e41d93bbd9cea4f5c6ef3647c8ea3c

**Comment by jbsbbn** [comment]
For what it's worth, it's an issue for us (the GPO) too.

And I really think that closing a ticket with no explanation of why -- whether the problem was fixed or not, what version / commit it was fixed in, etc -- isn't just a "development model" thing, it's bad programming practice.

**Comment by brandonheller** [comment]
Thanks Ali, I appreciate the extra time to reference issues to their fixes, and I think others will too.

**Comment by alshabib** [comment]
More often than not, issues are closed as part of a milestone which clearly indicates which version these bugs/issues where fixed for. But as I commented earlier, if fixes do not come as part of a milestone, I will attempt to point to a commit.

**Comment by jbsbbn** [comment]
Thanks; echoing Brandon, we appreciate it.

**Comment by brandonheller** [comment]
While we're on the subject, Ali, maybe you can help me understand something here.  The commit you referenced above, 446d926, addresses multiple errors, which means that I need to look through what is potentially a lot of code to find something simple like the error message that corresponds to a bugfix. 

Can you explain why multiple unrelated changes are being grouped into a single large commit?  Git/GitHub certainly supports pull requests with multiple, atomic, independent commits, so this just seems odd.  Thanks.

**Comment by alshabib** [comment]
That's because I stupidly fixed all those in one commit. I forgot to commit for each individual issue. Simple overlook on my part.

**Comment by brandonheller** [comment]
In the future, instead of committing the bag of unrelated commits, you can use 'git add -p' to add individual changes.  I find this functionality really useful for separating commits, or for when I have a small change that I don't want to commit, like a debug level change.

**Comment by alshabib** [comment]
Thanks for the tip.
