### ISSUE TITLE
more concise fvctl actions w/default empty password

### ISSUE THREAD

**Issue by brandonheller** [opennetworkinglab/flowvisor#197]
How about:

```
fvctl get-config
```

for a tutorial, rather than:

```
fvctl -f /dev/null get-config
```

This would be easier to get right and more consise: try a command with an empty password if none is provided on the CLI.

**Comment by brandonheller** [comment]
Was this fixed with a commit, or marked as won't-fix?

**Comment by alshabib** [comment]
fixed in 1.0.2
