### ISSUE TITLE
No error message when trying to run FV with another controller already running

### ISSUE THREAD

**Issue by brandonheller** [opennetworkinglab/flowvisor#203]
When another controller, like beacon or ovs-controller, is already running, flowvisor doesn't start, but it presents no errors.

10+ people found this confusing at the ONS tutorial.

**Comment by brandonheller** [comment]
Was this fixed with a commit, or marked as won't-fix?

**Comment by alshabib** [comment]
fixed in 1.0.2

**Comment by brandonheller** [comment]
What was the commit?  I know that future tutorial students will encounter this, so I want to know what to expect here.  Thanks.

**Comment by alshabib** [comment]
I forgot to catch the appropriate exception. The commit is ac9ead9426656175257374974dc30e3de47f026f
