### ISSUE TITLE
different result when running from script vs copying/pasting commands

### ISSUE THREAD

**Issue by brandonheller** [opennetworkinglab/flowvisor#207]
People came across this in the ONS tutorial and got pretty frustrated (as did I).

When you do the FlowVisor exercise for the ONS Tutorial, copying individual commands leads to success, but scripting those same exact commands leads to failure.   By failure, I mean that FV didn't connect to switches, or does weird behavior I can't reproduce.  Restarting flowvisor after running the script always seems to fix things, though.

Ali suggests that this is due to optimistically returning from fvctl commands without verifying their completion.  From a user's perspective, this is _extremely_ confusing.  The default show be the safe option, and the risky unsafe option should require an extra flag!  Thanks.

**Comment by jbsbbn** [comment]
This seems potentially very dangerous in the context of FOAM too, where several FOAM requests might come in at the same time. Having FlowVisor report success when it actually hasn't succeeded yet would make a real mess.

Can you mark this as one that the GPO cares about?

**Comment by leenheer** [comment]
Actually, Brandon describes a situation where FV reports failure for some commands when multiple come in. This looks like a bug, but someone else will have to confirm.

Also, FlowVisor's JSON API reports success as soon as a well-formed call comes in, before actually processing the call. This is imo perfectly fine, as users can query the geni_status through FOAM. This all in contrast to FV XMLRPC API which blocks calls until having fully processed it.

**Comment by nbastin** [comment]
I am completely unclear on how this is supposedly ok.  If FlowVisor reported some kind of job-id and said "please poll this later to find out what happened", that would be ok, but that is not what it does (nor is there any way to figure out whether any individual call succeeded).  Querying geni_status through FOAM should not be a valid response to flowvisor users, and indeed, that call uses xml-rpc, so clearly isn't a good thing since that API is supposedly deprecated in favor of the JSON one.

**Comment by brandonheller** [comment]
I actually don't know the underlying cause, but I do know that executing commands from a script results in different FV behavior than copying those in one-at-a-time.  _The suggested cause was just a conjecture from Ali._ It's a hypothesis that could use some validation.

The tutorial is here, and you can repeat the instructions - should just need an FV instance installed + mn2.0. 
https://github.com/onstutorial/onstutorial/wiki/Flowvisor-Exercise
I put the copy/paste instructions into a two scripts, which should help with replicating; you still need to do a few things at the top of the Flowvisor-Exercise script.
https://github.com/onstutorial/onstutorial/tree/master/flowvisor_scripts

**Comment by brandonheller** [comment]
Was this fixed with a commit, or marked as won't-fix?

**Comment by alshabib** [comment]
fixed in 1.0.2

**Comment by brandonheller** [comment]
Can you link to the commit?  I'd really like to know what the problem was here.  Saying 'fixed in 1.0.2' doesn't help me understand how it was fixed, and if the problem recurs, that knowledge could be useful.  Github automatically adds the link whenever you use a shortened SHA-1 in an Issue comment.

**Comment by alshabib** [comment]
The problem here was that there weren't enough threads to handle back to back requests. From my tests, the error was not occuring any more. The commit is ac9ead9426656175257374974dc30e3de47f026f

**Comment by brandonheller** [comment]
That description sounds like treating the symptom, rather than the problem.  If there are N threads and I make a script to run N+1 fvctl flowspace adds, will request N+1 fail silently, fail with an error, or pause and complete successfully?

This isn't just academic interest, I would issue as many requests as I have in parallel if they complete faster as a result.

**Comment by alshabib** [comment]
Well, the number of threads was ridiculously small, and now the requests are also inserted into a list for processing.

**Comment by brandonheller** [comment]
If there are more outstanding requests than available threads to process them, what happens?  Is there a JSON-RPC-specific error that gets returned?  Does the TCP connection for the JSON-RPC request never complete?  Does the request fail silently?

**Comment by alshabib** [comment]
If there are more requests than JSONRPC can handle, it should return an internal error message. The idea is to receive request, make sure they aren't malformed, and place them in a list for awaiting processing by the available threads. If something goes wrong, the server returns an internal error.
