### ISSUE TITLE
Flowspace rules should support ranges

### ISSUE THREAD

**Issue by gmcnaught** [opennetworkinglab/flowvisor#208]
When using flowvisor to create more than one slice,  the requirement of one flowspace rule per port, per vlan, means up to 4096 flowspace rules have to be added to flowvisor per port, or just over 700k flowspace rules to support a network with 18 switches and 10 ports per switch. This is compounded by the fact that flowspace rule insertion seems to take over 10 seconds per flowspace rule after only 20,000 flowspace rules are added.

Here are the results of our flowspace insert tests, using a bulk insert size of 100 flowspace rules per batch:

![Flowspace_Insert_Perf](https://f.cloud.github.com/assets/1371263/400293/ec7fa314-a89a-11e2-972e-6d01eae80f35.png)

Based on the growth pattern of insert time, we estimate it would take 34 days for us to insert all of the rules required for a fully defined flowspace ruleset.

For maintainability reasons in operations, it would be incredibly useful to be able to specify a vlan range within a flowspace rule, rather than having to specify each vlan individually.

**Comment by gmcnaught** [comment]
Here is a our current config with 26k slices

https://github.com/gmcnaught/flowvisor_config/blob/master/flowvisor_config.json

**Comment by mssumanth** [comment]
Hi, 

We are trying to work on this and trying to understand the use case of Internet2.(sorry it has been some time since we discussed this and I am not completely sure if I understand it) It would have been great if openflow switches themselves supported ranges/wildcards in the match fields, but as of now first we wanted to properly understand this issue. Would it be possible to explain in a little more detail as to why you have that many vlans? Is there no way of reducing the number of flowspace rules which has to be added for the 18 switches?

Thanks 
Sumanth

**Comment by gmcnaught** [comment]
Hi Sumanth,

We would like our slice allocation policy to use as low a level construct as possible to be conceptually simple for engineers and have the greatest chance for support within vendor offerings.  Today, vlan_id and port are both supported matches and actions by our vendors and providing a familiar traffic segregation construct to engineers.   

Within the AL2S networks there are 2 types of ports, customer facing and core side.
Customer facing interfaces have the constraint that this is where we pass traffic to customers and as such the vlan tag use must be agreed upon between customer and service provider.  Core side ports can pass traffic using any tags we wish, as its opaque to customers.  To provide the needed level of service separation, we believe that it will be necessary maintain non-overlapping VLAN tag space for each slice on a per port basis.  

Assume AL2S provide 3 services, OESS, OESS-EXP, Peering.  And lets assume that we have a customer Big U, which for legitimate reasons needs to define the tag space for his port as follows:
1.  VID 1           Peering
2.  VID 2-1000      OESS
3.  VID 1001-2000   OESS-Experimental

It is also the case that AL2S will provide non-Openflow services, because of this there might be another university Other U.  which defined policy as follows:
1.  VID 1-1000      Reserved for Native Forwarding
2.  VID 1001 – 1500   OESS
3.  VID 1501 – 3000   Reserved

The upshot is that each port can have an arbitrary VLAN Tag to slice mapping.

On the Core side, its slightly different in that there is central coordination of allocation by the AL2S administrators.   For the core side, a range of tags will be defined for each slice.  If a slice is allowed to operate on a given core side interface then it will be limited to its tag range.  Allocation policy might look something like this:
1.  VID 1 - 2000        OESS
2.  VID 2001 – 2500   OESS-EXP
3.  VID 2500 – 4096   Reserved for Future Use

While conceptually clean, this allocation policy has scaling impacts in Flowvisor because FlowVisor does not currently support defining policy on a range of vlan tags.  The number of policy rules required = 4096 \* total number of ports on the network.    Today we have ~ 10 ports per switch with a total of 18 switches.  As a result , our FlowSpace definition regardless of the number of slices will require 737,280 policy rules.
