### ISSUE TITLE
new passwd prompt gets NPE if non-terminal

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#21]
Status: Open
Project:    Flowvisor
Component/s:    Core
Affects Version/s:  0.7.2
Fix Version/s:  Long Term

Type:    Bug    Priority:    Major
Reporter:   Nick Bastin Assignee:   Nick Bastin
Resolution:  Unresolved Votes:   0
Labels:  None
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
fvctl listFlowSpace | less
causes an NPE
Just need to test and prompt

 Comments  
Comment by Nick Bastin [ 11/Jun/11 ]
This has the proper behaviour for me on Ubuntu 10.10, so I'm moving this to long term until someone can report an environment where this happens.
Comment by Rob Sherwood [ 04/Jul/11 ]
I believe this was partially fixed in:
commit 59104f6c62cca32fac3bc53a8015c7caeb0d353a
Author: Rob Sherwood rob.sherwood@stanford.edu
Date: Thu Mar 17 20:54:01 2011 -0700
made fvctl not throw NPE when called `fvctl | less`
System.console() returns null if called without
a direct tty... or something. Default to print
to stderr and for some reason it doesn't echo
the password characters.
But I left the bug open because while it works in the `fvctl | less` case, it still echo's the passwd in the `fvctl > output` case. Weird, huh?

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-34

**Comment by alshabib** [comment]
affects XMLRPC interface, which is deprecated.
