### ISSUE TITLE
fvctl set-config with no arguments seems to succeed

### ISSUE THREAD

**Issue by jbsbbn** [opennetworkinglab/flowvisor#214]
If you do 'fvctl set-config', you don't get an error. Should you? Or did something actually get set? 'fvctl help set-config' doesn't seem to say what happens if you don't specify any options.

**Comment by alshabib** [comment]
Nothing got set, not sure why this should be an error. You ask to set nothing, it sets nothing.

**Comment by jbsbbn** [comment]
I think that asking to set nothing is nonsensical, and should be a syntax error.

What's a situation where you would actually want to set nothing, and be glad that the command succeeded? I think a much more likely case is that you meant to set something, left off the thing you wanted to set, and that getting "success" as a result is misleading and confusing.
