### ISSUE TITLE
flowvisor reports a DPID twice with getSliceStats

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#22]
Status: Open
Project:    Flowvisor
Component/s:    Core
Affects Version/s:  0.7.2
Fix Version/s:  Next

Type:    Bug    Priority:    Major
Reporter:   Nick Bastin Assignee:   Rob Sherwood
Resolution:  Unresolved Votes:   0
Labels:  None
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
My rule of last resort points to my "beacon" slice. There are 2 OpenFlow? switches currently up on my network. DPID 00:5c:00:26:f1:1c:42:00 has an uplink to my non-OpenFlow? core switch (10 GB/s link) and nothing else. DPID 00:04:00:26:f1:1c:29:00 has a 1 GB/s uplink to the core switch and 3 Asterix demo machines, but nothing else. Both switches are HP 5406zl boxes running the latest (as of last week) OF firmware. Here is what getSliceStats shows:
root@flowvisor:/var/local/src/flowvisor# fvctl --passwd-file=/root/.fvp getSliceStats beacon
Got reply:
---Sent---
slicer_beacon_dpid=00:5c:00:26:f1:1c:42:00 :: ECHO_REQUEST=2,PACKET_IN=65204,HELLO=75,FLOW_REMOVED=6789
slicer_beacon_dpid=00:5c:00:26:f1:1c:42:00 :: ECHO_REQUEST=2,PACKET_IN=32152,HELLO=38,FLOW_REMOVED=3275
slicer_beacon_dpid=00:04:00:26:f1:1c:29:00 :: ECHO_REQUEST=2,PACKET_IN=98290,HELLO=114,FLOW_REMOVED=10346
Total :: ECHO_REQUEST=6,PACKET_IN=195646,HELLO=227,FLOW_REMOVED=20410
---Recv---
Total ::
---Drop---
slicer_beacon_dpid=00:5c:00:26:f1:1c:42:00 :: PACKET_IN=74991
slicer_beacon_dpid=00:5c:00:26:f1:1c:42:00 :: PACKET_IN=37224,FLOW_REMOVED=1
slicer_beacon_dpid=00:04:00:26:f1:1c:29:00 :: PACKET_IN=115029,FLOW_REMOVED=3
Total :: PACKET_IN=227244,FLOW_REMOVED=4

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-32

**Comment by alshabib** [comment]
affects XMLRPC interface, which is deprecated.
