### ISSUE TITLE
FlowVisor unwanted shutdown after 'Connection is closed.' message

### ISSUE THREAD

**Issue by alshabib** [opennetworkinglab/flowvisor#222]
I have tried to reproduce the bug with little success. I am creating this ticket so that we can track any extra info about this bug.

 Apr 29 00:53:03 tulum -1>Apr 29 00:53:03 flowvisor: WARN none : No match for: OFMatch[in_port=5,dl_dst=ff:ff:ff:ff:ff:ff,dl_src=00:1b:21:4b:3e:e9,dl_type=0x806,dl_vlan=65535,dl_vpcp=0,nw_dst=10.42.104.55,nw_src=10.42.104.52,nw_proto=1,nw_tos=0,tp_dst=1,tp_src=0] 
 Apr 29 00:53:03 tulum -1>Apr 29 00:53:03 flowvisor: WARN none : No match for: OFMatch[in_port=5,dl_dst=ff:ff:ff:ff:ff:ff,dl_src=00:1b:21:4b:3e:e9,dl_type=0x806,dl_vlan=65535,dl_vpcp=0,nw_dst=10.42.106.95,nw_src=10.42.106.52,nw_proto=1,nw_tos=0,tp_dst=1,tp_src=0] 
 Apr 29 00:53:03 tulum -1>Apr 29 00:53:03 flowvisor: WARN none : No match for: OFMatch[in_port=5,dl_dst=ff:ff:ff:ff:ff:ff,dl_src=00:1b:21:4b:3f:ad,dl_type=0x806,dl_vlan=65535,dl_vpcp=0,nw_dst=10.42.106.95,nw_src=10.42.106.51,nw_proto=1,nw_tos=0,tp_dst=1,tp_src=0] 
 Apr 29 00:53:03 tulum -1>Apr 29 00:53:03 flowvisor: WARN none : No match for: OFMatch[in_port=5,dl_dst=ff:ff:ff:ff:ff:ff,dl_src=00:26:b9:7e:6c:c8,dl_type=0x806,dl_vlan=65535,dl_vpcp=0,nw_dst=10.37.16.53,nw_src=10.37.16.100,nw_proto=1,nw_tos=0,tp_dst=1,tp_src=0] 
 Apr 29 00:53:04 tulum -1>Apr 29 00:53:04 flowvisor: WARN none : No match for: OFMatch[in_port=5,dl_dst=ff:ff:ff:ff:ff:ff,dl_src=00:1b:21:4b:3e:e9,dl_type=0x806,dl_vlan=65535,dl_vpcp=0,nw_dst=10.42.104.55,nw_src=10.42.104.52,nw_proto=1,nw_tos=0,tp_dst=1,tp_src=0] 
 Apr 29 00:53:04 tulum -1>Apr 29 00:53:04 flowvisor: WARN none : No match for: OFMatch[in_port=5,dl_dst=ff:ff:ff:ff:ff:ff,dl_src=00:1b:21:4b:3e:e9,dl_type=0x806,dl_vlan=65535,dl_vpcp=0,nw_dst=10.42.106.95,nw_src=10.42.106.52,nw_proto=1,nw_tos=0,tp_dst=1,tp_src=0] 
 Apr 29 00:53:04 tulum -1>Apr 29 00:53:04 flowvisor: INFO classifier-dpid=06:d6:00:24:a8:c4:b9:00 : dynamically removing port 34 
 Apr 29 00:53:04 tulum -1>Apr 29 00:53:04 flowvisor: WARN none : Connection is closed. 
 Apr 29 00:53:04 tulum -1>Apr 29 00:53:04 flowvisor: INFO none : Shutting down config database. 
 Apr 29 01:42:17 tulum puppetd[4474]: (//Node[tulum]/geni::lab::foam::server::production/flowvisor::server/Service[flowvisor]/ensure) ensure changed 'stopped' to 'running'
 Apr 29 01:42:18 tulum puppetd[4474]: (//Node[tulum]/geni::lab::foam::server::production/flowvisor::server/Exec[flowvisor_check_config]/returns) executed successfully
 Apr 29 01:42:18 tulum -1>Apr 29 01:42:18 flowvisor: INFO started flowvisor logger

**Comment by alshabib** [comment]
Logs say it died here:

First Crash:

Apr 30 18:47:05 2013-04-30 18: 47:05,317 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) none : 'Statement' already closed.
Apr 30 18:47:05 2013-04-30 18: 47:05,317 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) none : 'Statement' already closed.

in debug log:

Apr 30 18:47:05 2013-04-30 18: 47:05,337 DEBUG org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:204) execute: 
Request performed successfully
Apr 30 18:47:05 2013-04-30 18: 47:05,338 DEBUG org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:252) execute: 
<-
Apr 30 18:47:05 2013-04-30 18: 47:05,362 DEBUG org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:192) execute: 
->
Apr 30 18:47:05 2013-04-30 18: 47:05,416 DEBUG org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:204) execute: 
Request performed successfully
Apr 30 18:47:05 2013-04-30 18: 47:05,416 DEBUG org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:252) execute: 
<-
Apr 30 18:47:05 2013-04-30 18: 47:05,440 DEBUG org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:192) execute: 
->
Apr 30 19:41:02 2013-04-30 19: 41:02,561 DEBUG org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:192) execute: 
->
Apr 30 19:41:02 2013-04-30 19: 41:02,848 DEBUG org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:204) execute: 
Request performed successfully
Apr 30 19:41:02 2013-04-30 19: 41:02,854 DEBUG org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:252) execute: 
<-
Apr 30 19:41:02 2013-04-30 19: 41:02,902 DEBUG org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:192) execute: 
->
Apr 30 19:41:02 2013-04-30 19: 41:02,947 DEBUG org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:204) execute: 
Request performed successfully
Apr 30 19:41:02 2013-04-30 19: 41:02,948 DEBUG org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:252) execute: 
<-
Apr 30 19:41:02 2013-04-30 19: 41:02,979 DEBUG org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:192) execute:

Second Crash (slightly more context. Debug log showed the same as above ): 

May  1 05:57:07 2013-05-01 05: 57:07,110 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) classifier-dpid=06:d6:00:12:e2:22:63:1d : dropping msg with unknown xid: ofmsg:v=1;t=ERROR;l
=76;x=0;c=4;t=2;msg=OFPacketOut [actionFactory=org.flowvisor.message.FVMessageFactory@21b6ce33, actions=[], actionsLength=0, bufferId=0xb300f10d, inPort=15, packetData=[]];actions=DROP;err=
[64]
May  1 05:57:07 2013-05-01 05: 57:07,110 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) classifier-dpid=06:d6:00:12:e2:22:63:1d : dropping msg with unknown xid: ofmsg:v=1;t=ERROR;l
=76;x=0;c=4;t=2;msg=OFPacketOut [actionFactory=org.flowvisor.message.FVMessageFactory@21b6ce33, actions=[], actionsLength=0, bufferId=0xb300f10d, inPort=15, packetData=[]];actions=DROP;err=
[64]
May  1 05:57:07 2013-05-01 05: 57:07,181 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) classifier-dpid=06:d6:00:12:e2:22:81:42 : dropping msg with unknown xid: ofmsg:v=1;t=ERROR;l
=76;x=0;c=4;t=2;msg=OFPacketOut [actionFactory=org.flowvisor.message.FVMessageFactory@19e25176, actions=[], actionsLength=0, bufferId=0xfcf1ac8e, inPort=15, packetData=[]];actions=DROP;err=
[64]
May  1 05:57:07 2013-05-01 05: 57:07,181 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) classifier-dpid=06:d6:00:12:e2:22:81:42 : dropping msg with unknown xid: ofmsg:v=1;t=ERROR;l
=76;x=0;c=4;t=2;msg=OFPacketOut [actionFactory=org.flowvisor.message.FVMessageFactory@19e25176, actions=[], actionsLength=0, bufferId=0xfcf1ac8e, inPort=15, packetData=[]];actions=DROP;err=
[64]
May  1 05:57:07 2013-05-01 05: 57:07,315 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) classifier-dpid=06:d6:00:12:e2:22:81:42 : dropping msg with unknown xid: ofmsg:v=1;t=ERROR;l
=76;x=0;c=4;t=2;msg=OFPacketOut [actionFactory=org.flowvisor.message.FVMessageFactory@19e25176, actions=[], actionsLength=0, bufferId=0xfcf1b48f, inPort=15, packetData=[]];actions=DROP;err=
[64]
May  1 05:57:07 2013-05-01 05: 57:07,315 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) classifier-dpid=06:d6:00:12:e2:22:81:42 : dropping msg with unknown xid: ofmsg:v=1;t=ERROR;l
=76;x=0;c=4;t=2;msg=OFPacketOut [actionFactory=org.flowvisor.message.FVMessageFactory@19e25176, actions=[], actionsLength=0, bufferId=0xfcf1b48f, inPort=15, packetData=[]];actions=DROP;err=
[64]
May  1 05:57:07 2013-05-01 05: 57:07,431 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) classifier-dpid=06:dc:00:12:e2:22:63:6e : inserting drop (hard=0,idle=1) rule for FlowEntry[
dpid=[06:dc:00:12:e2:22:63:6e],ruleMatch=[OFMatch[]],actionsList=[Slice:58dade33-4477-4628-8ffd-e288eb056f22=4],id=[1463],priority=[100],]
May  1 05:57:07 2013-05-01 05: 57:07,431 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) classifier-dpid=06:dc:00:12:e2:22:63:6e : inserting drop (hard=0,idle=1) rule for FlowEntry[
dpid=[06:dc:00:12:e2:22:63:6e],ruleMatch=[OFMatch[]],actionsList=[Slice:58dade33-4477-4628-8ffd-e288eb056f22=4],id=[1463],priority=[100],]
May  1 05:57:07 2013-05-01 05: 57:07,473 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) classifier-dpid=06:df:00:12:e2:22:63:6e : inserting drop (hard=0,idle=1) rule for FlowEntry[
dpid=[06:df:00:12:e2:22:63:6e],ruleMatch=[OFMatch[]],actionsList=[Slice:58dade33-4477-4628-8ffd-e288eb056f22=4],id=[1472],priority=[100],]
May  1 05:57:07 2013-05-01 05: 57:07,473 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) classifier-dpid=06:df:00:12:e2:22:63:6e : inserting drop (hard=0,idle=1) rule for FlowEntry[
dpid=[06:df:00:12:e2:22:63:6e],ruleMatch=[OFMatch[]],actionsList=[Slice:58dade33-4477-4628-8ffd-e288eb056f22=4],id=[1472],priority=[100],]
May  1 05:57:07 2013-05-01 05: 57:07,572 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) slicer_58dade33-4477-4628-8ffd-e288eb056f22_dpid=06:db:00:12:e2:22:63:6e : dropping msg: con
troller not connected: ofmsg:v=1;t=FLOW_REMOVED;l=88;x=766061;OFMatch[in_port=1,dl_dst=01:00:0c:cc:cc:cd,dl_src=00:11:bb:17:a5:91,dl_type=0x32,dl_vlan=0xffff,dl_vpcp=0,nw_dst=0.0.0.0,nw_src
=0.0.0.0,nw_proto=0,nw_tos=0,tp_dst=0,tp_src=0]
May  1 05:57:07 2013-05-01 05: 57:07,572 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) slicer_58dade33-4477-4628-8ffd-e288eb056f22_dpid=06:db:00:12:e2:22:63:6e : dropping msg: con
troller not connected: ofmsg:v=1;t=FLOW_REMOVED;l=88;x=766061;OFMatch[in_port=1,dl_dst=01:00:0c:cc:cc:cd,dl_src=00:11:bb:17:a5:91,dl_type=0x32,dl_vlan=0xffff,dl_vpcp=0,nw_dst=0.0.0.0,nw_src
=0.0.0.0,nw_proto=0,nw_tos=0,tp_dst=0,tp_src=0]
May  1 05:57:07 2013-05-01 05: 57:07,575 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) slicer_58dade33-4477-4628-8ffd-e288eb056f22_dpid=06:de:00:12:e2:22:63:6e : dropping msg: con
troller not connected: ofmsg:v=1;t=FLOW_REMOVED;l=88;x=764369;OFMatch[in_port=1,dl_dst=01:00:0c:cc:cc:cd,dl_src=00:11:bb:17:a5:91,dl_type=0x32,dl_vlan=0xffff,dl_vpcp=0,nw_dst=0.0.0.0,nw_src
=0.0.0.0,nw_proto=0,nw_tos=0,tp_dst=0,tp_src=0]
May  1 05:57:07 2013-05-01 05: 57:07,575 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) slicer_58dade33-4477-4628-8ffd-e288eb056f22_dpid=06:de:00:12:e2:22:63:6e : dropping msg: con
troller not connected: ofmsg:v=1;t=FLOW_REMOVED;l=88;x=764369;OFMatch[in_port=1,dl_dst=01:00:0c:cc:cc:cd,dl_src=00:11:bb:17:a5:91,dl_type=0x32,dl_vlan=0xffff,dl_vpcp=0,nw_dst=0.0.0.0,nw_src
=0.0.0.0,nw_proto=0,nw_tos=0,tp_dst=0,tp_src=0]
May  1 05:57:07 2013-05-01 05: 57:07,733 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) classifier-dpid=06:d6:00:12:e2:22:63:1d : dropping msg with unknown xid: ofmsg:v=1;t=ERROR;l=76;x=0;c=4;t=2;msg=OFPacketOut [actionFactory=org.flowvisor.message.FVMessageFactory@21b6ce33, actions=[], actionsLength=0, bufferId=0xb3011131, inPort=13, packetData=[]];actions=DROP;err=[64]
May  1 05:57:07 2013-05-01 05: 57:07,733 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) classifier-dpid=06:d6:00:12:e2:22:63:1d : dropping msg with unknown xid: ofmsg:v=1;t=ERROR;l=76;x=0;c=4;t=2;msg=OFPacketOut [actionFactory=org.flowvisor.message.FVMessageFactory@21b6ce33, actions=[], actionsLength=0, bufferId=0xb3011131, inPort=13, packetData=[]];actions=DROP;err=[64]
May  1 05:57:07 2013-05-01 05: 57:07,920 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) none : 'Statement' already closed.
May  1 05:57:07 2013-05-01 05: 57:07,920 WARN org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) none : 'Statement' already closed.

**Comment by alshabib** [comment]
May  2 00:23:06 2013-05-02 00: 23:06,219 WARN
org.flowvisor.log.AnyLogger.log(AnyLogger.java:43)
classifier-dpid=06:d6:00:12:e2:22:81:42 : dropping msg with unknown xid:
ofms
g:v=1;t=ERROR;l=76;x=0;c=4;t=2;msg=OFPacketOut
[actionFactory=org.flowvisor.message.FVMessageFactory@4ce6245a,
actions=[], actionsLength=0, bufferId=0x18032053, inPort=15, pa
cketData=[]];actions=DROP;err=[64]
May  2 00:23:06 2013-05-02 00: 23:06,251 WARN
org.flowvisor.log.AnyLogger.log(AnyLogger.java:43)
classifier-dpid=06:d6:00:12:e2:22:81:42 : dropping msg with unknown xid:
ofms
g:v=1;t=ERROR;l=76;x=0;c=4;t=2;msg=OFPacketOut
[actionFactory=org.flowvisor.message.FVMessageFactory@4ce6245a,
actions=[], actionsLength=0, bufferId=0x18032454, inPort=13, pa
cketData=[]];actions=DROP;err=[64]
May  2 00:23:06 2013-05-02 00: 23:06,251 WARN
org.flowvisor.log.AnyLogger.log(AnyLogger.java:43)
classifier-dpid=06:d6:00:12:e2:22:81:42 : dropping msg with unknown xid:
ofms
g:v=1;t=ERROR;l=76;x=0;c=4;t=2;msg=OFPacketOut
[actionFactory=org.flowvisor.message.FVMessageFactory@4ce6245a,
actions=[], actionsLength=0, bufferId=0x18032454, inPort=13, pa
cketData=[]];actions=DROP;err=[64]
May  2 00:23:06 2013-05-02 00: 23:06,412 WARN
org.flowvisor.log.AnyLogger.log(AnyLogger.java:43)
slicer_58dade33-4477-4628-8ffd-e288eb056f22_dpid=06:db:00:12:e2:22:63:6e
: dr
opping msg: controller not connected:
ofmsg:v=1;t=FLOW_REMOVED;l=88;x=831687;OFMatch[in_port=1,dl_dst=01:00:0c:cc:cc:cd,dl_src=00:11:bb:17:a5:91,dl_type=0x32,dl_vlan=0xffff,d
l_vpcp=0,nw_dst=0.0.0.0,nw_src=0.0.0.0,nw_proto=0,nw_tos=0,tp_dst=0,tp_src=0]
May  2 00:23:06 2013-05-02 00: 23:06,412 WARN
org.flowvisor.log.AnyLogger.log(AnyLogger.java:43)
slicer_58dade33-4477-4628-8ffd-e288eb056f22_dpid=06:db:00:12:e2:22:63:6e
: dr
opping msg: controller not connected:
ofmsg:v=1;t=FLOW_REMOVED;l=88;x=831687;OFMatch[in_port=1,dl_dst=01:00:0c:cc:cc:cd,dl_src=00:11:bb:17:a5:91,dl_type=0x32,dl_vlan=0xffff,d
l_vpcp=0,nw_dst=0.0.0.0,nw_src=0.0.0.0,nw_proto=0,nw_tos=0,tp_dst=0,tp_src=0]
May  2 00:23:06 2013-05-02 00: 23:06,414 WARN
org.flowvisor.log.AnyLogger.log(AnyLogger.java:43)
slicer_58dade33-4477-4628-8ffd-e288eb056f22_dpid=06:dc:00:12:e2:22:63:6e
: dr
opping msg: controller not connected:
ofmsg:v=1;t=FLOW_REMOVED;l=88;x=830209;OFMatch[in_port=1,dl_dst=01:00:0c:cc:cc:cd,dl_src=00:11:bb:17:a5:91,dl_type=0x32,dl_vlan=0xffff,d
l_vpcp=0,nw_dst=0.0.0.0,nw_src=0.0.0.0,nw_proto=0,nw_tos=0,tp_dst=0,tp_src=0]
May  2 00:23:06 2013-05-02 00: 23:06,414 WARN
org.flowvisor.log.AnyLogger.log(AnyLogger.java:43)
slicer_58dade33-4477-4628-8ffd-e288eb056f22_dpid=06:dc:00:12:e2:22:63:6e
: dr
opping msg: controller not connected:
ofmsg:v=1;t=FLOW_REMOVED;l=88;x=830209;OFMatch[in_port=1,dl_dst=01:00:0c:cc:cc:cd,dl_src=00:11:bb:17:a5:91,dl_type=0x32,dl_vlan=0xffff,d
l_vpcp=0,nw_dst=0.0.0.0,nw_src=0.0.0.0,nw_proto=0,nw_tos=0,tp_dst=0,tp_src=0]
May  2 00:23:06 2013-05-02 00: 23:06,417 WARN
org.flowvisor.log.AnyLogger.log(AnyLogger.java:43)
slicer_58dade33-4477-4628-8ffd-e288eb056f22_dpid=06:df:00:12:e2:22:63:6e
: dr
opping msg: controller not connected:
ofmsg:v=1;t=FLOW_REMOVED;l=88;x=830043;OFMatch[in_port=1,dl_dst=01:00:0c:cc:cc:cd,dl_src=00:11:bb:17:a5:91,dl_type=0x32,dl_vlan=0xffff,d
l_vpcp=0,nw_dst=0.0.0.0,nw_src=0.0.0.0,nw_proto=0,nw_tos=0,tp_dst=0,tp_src=0]
May  2 00:23:06 2013-05-02 00: 23:06,417 WARN
org.flowvisor.log.AnyLogger.log(AnyLogger.java:43)
slicer_58dade33-4477-4628-8ffd-e288eb056f22_dpid=06:df:00:12:e2:22:63:6e
: dr
opping msg: controller not connected:
ofmsg:v=1;t=FLOW_REMOVED;l=88;x=830043;OFMatch[in_port=1,dl_dst=01:00:0c:cc:cc:cd,dl_src=00:11:bb:17:a5:91,dl_type=0x32,dl_vlan=0xffff,d
l_vpcp=0,nw_dst=0.0.0.0,nw_src=0.0.0.0,nw_proto=0,nw_tos=0,tp_dst=0,tp_src=0]
May  2 00:23:06 2013-05-02 00: 23:06,439 WARN
org.flowvisor.log.AnyLogger.log(AnyLogger.java:43)
classifier-dpid=06:d6:00:12:e2:22:63:1d : dropping msg with unknown xid:
ofms
g:v=1;t=ERROR;l=76;x=0;c=4;t=2;msg=OFPacketOut
[actionFactory=org.flowvisor.message.FVMessageFactory@5e3e957c,
actions=[], actionsLength=0, bufferId=0xdcac5852, inPort=15, pa
cketData=[]];actions=DROP;err=[64]
May  2 00:23:06 2013-05-02 00: 23:06,439 WARN
org.flowvisor.log.AnyLogger.log(AnyLogger.java:43)
classifier-dpid=06:d6:00:12:e2:22:63:1d : dropping msg with unknown xid:
ofms
g:v=1;t=ERROR;l=76;x=0;c=4;t=2;msg=OFPacketOut
[actionFactory=org.flowvisor.message.FVMessageFactory@5e3e957c,
actions=[], actionsLength=0, bufferId=0xdcac5852, inPort=15, pa
cketData=[]];actions=DROP;err=[64]
May  2 00:23:06 2013-05-02 00: 23:06,526 WARN
org.flowvisor.log.AnyLogger.log(AnyLogger.java:43)
classifier-dpid=06:dc:00:12:e2:22:63:6e : inserting drop (hard=0,idle=1)
rule
for
FlowEntry[dpid=[06:dc:00:12:e2:22:63:6e],ruleMatch=[OFMatch[]],actionsList=[Slice:58dade33-4477-4628-8ffd-e288eb056f22=4],id=[1463],priority=[100],]
May  2 00:23:06 2013-05-02 00: 23:06,526 WARN
org.flowvisor.log.AnyLogger.log(AnyLogger.java:43)
classifier-dpid=06:dc:00:12:e2:22:63:6e : inserting drop (hard=0,idle=1)
rule
for
FlowEntry[dpid=[06:dc:00:12:e2:22:63:6e],ruleMatch=[OFMatch[]],actionsList=[Slice:58dade33-4477-4628-8ffd-e288eb056f22=4],id=[1463],priority=[100],]
May  2 00:23:06 2013-05-02 00: 23:06,550 WARN
org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) none : Connection
org.apache.derby.impl.jdbc.EmbedConnection40@449459787 (XID
= 243116043), (SESSIONID = 1052723), (DATABASE =
/usr/local/share/db/flowvisor/FlowVisorDB), (DRDAID = null)  is closed.
May  2 00:23:06 2013-05-02 00: 23:06,550 WARN
org.flowvisor.log.AnyLogger.log(AnyLogger.java:43) none : Connection
org.apache.derby.impl.jdbc.EmbedConnection40@449459787 (XID
= 243116043), (SESSIONID = 1052723), (DATABASE =
/usr/local/share/db/flowvisor/FlowVisorDB), (DRDAID = null)  is closed.

**Comment by alshabib** [comment]
potential fix in 1.0.4 and 9ad9daf3ce8b3d4be6a22d021455e401e88d6d18

I will not close this until it is completely fixed. Once we are happy, it will be applied to the DEV branch.

**Comment by gth828r** [comment]
FYI, we have updated a few sites to FV 1.0.8-1, and since then, we haven't been seeing this kind of crash.  It used to happen at Internet2 a few times a week, but it hasn't happened there since we upgraded.

**Comment by alshabib** [comment]
Great. Can we consider this issue closed in your opinion?

## 

Ali Al-Shabibi (sent from handheld)

**Comment by gth828r** [comment]
My guess is that things are fine, but let me consult with Josh (probably next week) before we close this out.

**Comment by jbsbbn** [comment]
We think the recent SoX crashes are not this bug? If not, I think we can close this one.

**Comment by gth828r** [comment]
I think the SoX crashes were unrelated.  I haven't seen any since Russ said something about increasing the memory on the host, although I don't know if he ended up doing that or not.

I think this one can be closed!

**Comment by alshabib** [comment]
fixed in 9ad9daf3ce8b3d4be6a22d021455e401e88d6d18 and in version 1.0.4
