### ISSUE TITLE
Error adding flowspace rules with MAC addresses

### ISSUE THREAD

**Issue by jbsbbn** [opennetworkinglab/flowvisor#232]
When I try to add a flowspace rule with a MAC address (dl_src or dl_dst), I get an error:

```
+$ fvctl --passwd-file=/etc/flowvisor.passwd add-flowspace regressionspace 00:ad:da:de:ad:fa:ca:de 1 dl_src=ca:fe:be:ef:fa:ce regressionslice=4
Traceback (most recent call last):
  File "/usr/bin/fvctl", line 1014, in <module>
do_func(gopts, opts, args)
  File "/usr/bin/fvctl", line 311, in do_addFlowSpace
match = makeMatch(args[3])
  File "/usr/bin/fvctl", line 709, in makeMatch
match[mstr] = func(it[1])
  File "/usr/bin/fvctl", line 755, in toInt
return int(val)
ValueError: invalid literal for int() with base 10: 'ca:fe:be:ef:fa:ce'
```

Why does it think "ca:fe:be:ef:fa:ce" is an "int() with base 10"?

(Or am I using the wrong format? The man page says "dl_src=mac // Matches Ethernet source address mac, which should be specified as 6 pairs of hexadecimal digits delimited by colons, e.g. 00:0A:E4:25:6B:B0." so it seems like it's looking for the format I'm using... I also tried uppercase in case that was the issue, but got the same result.)

**Comment by alshabib** [comment]
fixed in 1.0.6 as well
