### ISSUE TITLE
need to flush old flow entries

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#24]
Status: Open
Project:    Flowvisor
Component/s:    Core
Affects Version/s:  0.7.2
Fix Version/s:  Long Term

Type:    Bug    Priority:    Minor
Reporter:   Nick Bastin Assignee:   Rob Sherwood
Resolution:  Unresolved Votes:   0
Labels:  None
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
When you delete a slice, not only should you flush the flow entries from the FV's flowtable, you should probably also flush them from the switch. The first now works, but FV does not yet flush them from the switch.

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-13

**Comment by alshabib** [comment]
Implemented in 1.0
