### ISSUE TITLE
JSON API Documentation is incorrect for 'list-links'

### ISSUE THREAD

**Issue by nikr** [opennetworkinglab/flowvisor#245]
In the [JSON API Documentation](https://github.com/OPENNETWORKINGLAB/flowvisor/wiki/API-Changes), the response for `list-links` has fields called `src-dpid`, `src-port`, `dst-dpid` and `dst-port`, but the actual fields that are returned are called `srcDPID` and `srcPort`, `dstDPID` and `dstPort`. 

This should be either fixed in the code (I believe it's in org.flowvisor.api.LinkAdvertisement toMap() and fromMap() ) or in the API documentation.

**Comment by alshabib** [comment]
fixed in documentation. Thanks for reporting.
