### ISSUE TITLE
Flowspace entries and non-existent slices

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#25]
Status: Open
Project:    Flowvisor
Component/s:    Core
Affects Version/s:  0.7.2
Fix Version/s:  Long Term

Type:    Bug    Priority:    Minor
Reporter:   Nick Bastin Assignee:   Rob Sherwood
Resolution:  Unresolved Votes:   0
Labels:  None
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
If you delete a slice with fvctl, it also deletes all of the flowspace rules pointing to that slice. However, you can still add a flowspace rule with fvctl that points to a non-existent slice, which seems inconsistent.

 Comments  
Comment by Nick Bastin [ 27/Apr/11 ](from jbs in trac)
My two cents: I can see some advantage in allowing you to delete a slice and recreate it with the same name, and have the existing flowspace entries remain intact; and thus, also, to create flowspace entries that point to a slice that doesn't exist (yet).
Maybe an interface like
fvctl deleteSlice [ --preserve-flowspace ] <slicename>
fvctl addFlowSpace  [--force ] <dpid> <priority> <match> <actions>
so that by default, deleting a slice removes your flowspace entries, but you can override it if you want to preserve them; and by default, adding a flowspace entry to a slice that doesn't exist gives you an error (or a warning) but you can override that if you really want to do this? That seems like it'd do what most people want by default, but let people who want to do something slightly complicated still do so, without too much trouble.

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-12

**Comment by alshabib** [comment]
Anyone feel strongly about the preserve flowspace feature? Thinking of merging it with -> https://github.com/OPENNETWORKINGLAB/flowvisor/issues/60

**Comment by alshabib** [comment]
functionality moved to #60
