### ISSUE TITLE
Slice created but not visible in list-slices command

### ISSUE THREAD

**Issue by SAKSHIC** [opennetworkinglab/flowvisor#272]
Hello All,

I am able to create slices successfully but it is not appearing in list-slices command.
Pl. reply.

Regards,
Sakshi

**Comment by alshabib** [comment]
Is there an error in the flowvisor log?

**Comment by SAKSHIC** [comment]
It is possible but when I am creating flowspace using the slice which is created successfully  then also it is showing slice does not exist.

**Comment by SAKSHIC** [comment]
How to check the FV log??

**Comment by alshabib** [comment]
You need to look in the syslog of your machine, usually /var/log/messages

**Comment by SAKSHIC** [comment]
I am not able to get log files. Below are the commands and messages that I am getting...
1.    ./fvctl-json.py list-slices
   Password:
   Configured slices:
   fvadmin         --> enabled
2.    ./fvctl-json.py -f /dev/null add-slice upper tcp:localhost:10001 admin@upperslice
   Slice password:
   Slice upper was successfully created
3.    ./fvctl-json.py list-slices
   Password:
   Configured slices:
   fvadmin         --> enabled

Thanks & Regards,
Sakshi

**Comment by SAKSHIC** [comment]
In version 0.8 it is working fine.

**Comment by alshabib** [comment]
Make sure you are starting flowvisor as the flowvisor user. 

start it either with:

$ sudo /etc/init.d/flowvisor start
or
$ sudo -u flowvisor flowvisor

**Comment by tarekbouali** [comment]
Hi,
I am facing the same problem. Am running flowvisor as u said ali, but not working.
Could you please tell me how did you resolve this issue or give me a push to solve it? It has been long time that am running on this issue.

thanks in advance.

**Comment by ayoubezzabi** [comment]
in addition to other problems , i am facing the same problem here :(

**Comment by fadlyfptr** [comment]
> In version 0.8 it is working fine.

Do you know how to downgrade flowvisor 1.4 to 0.8? i have the same problem with add-slices
