### ISSUE TITLE
[BUG] Hello Message Sync Error

### ISSUE THREAD

**Issue by heycwkim** [opennetworkinglab/flowvisor#276]
Hello, Flowvisor developer.

I want to report a bug when the lastest Flowvisor and SDN Openflow Controller send Openflow message to each other.

Environment: Ubuntu 12.04 LTS, the lastest Flowvisor(updated version:14/07/08), SDN Controller supported by OF 1.4(Mul/Ryu)

After I configure SDN controller Ip address of any slice in flowvisor, the Flowvisor is connected with SDN Controller by TCP. And then the Flowvisor first send OF message(HELLO) the SDN Controller. In this condition, the Flowvisor works well regardless of the Openflow version.

But if OF 1.3 SDN controller first send the Flowvisor Hello Message to notify the lastest OF verison, the Flowvisor can't control it and arise exception error as below;
java.nio.BufferUnderflowException
     at java.nio.Buffer.nextGetIndex(Buffer.java:506)
     at java.nio.DirectByteBuffer.getShort(DirectByteBuffer.java:586)
     at org.openflow.protocol.OFError.readFrom(OFError.java:208)
     at org.openflow.protocol.factory.BasicFactory.parseMessages(BasicFactory.java:68)
     at org.openflow.io.OFMessageAsyncStream.read(OFMessageAsyncStream.java:54)
     at org.flowvisor.io.FVMessageAsyncStream.read(FVMessageAsyncStream.java:86)
     at org.openflow.io.OFMessageAsyncStream.read(OFMessageAsyncStream.java:44)
     at org.flowvisor.slicer.FVSlicer.handleIOEvent(FVSlicer.java:568)
     at org.flowvisor.slicer.FVSlicer.handleEvent(FVSlicer.java:466)
     at org.flowvisor.events.FVEventLoop.doEventLoop(FVEventLoop.java:168)
     at org.flowvisor.FlowVisor.run(FlowVisor.java:198)
     at org.flowvisor.FlowVisor.main(FlowVisor.java:231)

In conculsion, I think you have to prevent this error, even if the flowvisor not support the lastest Openflow version. In addition, I can't try to fix this bug, because the flowvisor use your customized jar files including class code.

Thanks and Regard Changwoo.

**Comment by alshabib** [comment]
It seems you are using a very old flowvisor from 2008, correct? If yes please update to flowvisor 1.4. 

## 

Ali Al-Shabibi (sent from handheld)

**Comment by heycwkim** [comment]
First, I'm sorry to be late for your reply e-mail.

Even if I check one more my flowvisor version, it's the lastest flowvisor
installed from 1.4-MAINT of git branches.

So I think you check initial Openflow sequence(from hello message to
feature message) of your flowvisor using SDN Controller (e.g. OpenMuL 1.3,
Ryu 1.3).

Thanks and Regards Changwoo.

2014-07-10 19:25 GMT+09:00 Ali Al-Shabibi notifications@github.com:

> It seems you are using a very old flowvisor from 2008, correct? If yes
> please update to flowvisor 1.4.
> 
> ## 
> 
> Ali Al-Shabibi (sent from handheld)
> 
> > On Jul 9, 2014, at 6:21 AM, "Changwoo, Kim" notifications@github.com
> > wrote:
> > 
> > Hello, Flowvisor developer.
> > 
> > I want to report a bug when the lastest Flowvisor and SDN Openflow
> > Controller send Openflow message to each other.
> > 
> > Environment: Ubuntu 12.04 LTS, the lastest Flowvisor(updated
> > version:14/07/08), SDN Controller supported by OF 1.4(Mul/Ryu)
> > 
> > After I configure SDN controller Ip address of any slice in flowvisor,
> > the Flowvisor is connected with SDN Controller by TCP. And then the
> > Flowvisor first send OF message(HELLO) the SDN Controller. In this
> > condition, the Flowvisor works well regardless of the Openflow version.
> > 
> > But if OF 1.3 SDN controller first send the Flowvisor Hello Message to
> > notify the lastest OF verison, the Flowvisor can't control it and arise
> > exception error as below;
> > java.nio.BufferUnderflowException
> > at java.nio.Buffer.nextGetIndex(Buffer.java:506)
> > at java.nio.DirectByteBuffer.getShort(DirectByteBuffer.java:586)
> > at org.openflow.protocol.OFError.readFrom(OFError.java:208)
> > at
> > org.openflow.protocol.factory.BasicFactory.parseMessages(BasicFactory.java:68)
> > 
> > at
> > org.openflow.io.OFMessageAsyncStream.read(OFMessageAsyncStream.java:54)
> > at
> > org.flowvisor.io.FVMessageAsyncStream.read(FVMessageAsyncStream.java:86)
> > at
> > org.openflow.io.OFMessageAsyncStream.read(OFMessageAsyncStream.java:44)
> > at org.flowvisor.slicer.FVSlicer.handleIOEvent(FVSlicer.java:568)
> > at org.flowvisor.slicer.FVSlicer.handleEvent(FVSlicer.java:466)
> > at org.flowvisor.events.FVEventLoop.doEventLoop(FVEventLoop.java:168)
> > at org.flowvisor.FlowVisor.run(FlowVisor.java:198)
> > at org.flowvisor.FlowVisor.main(FlowVisor.java:231)
> > 
> > In conculsion, I think you have to prevent this error, even if the
> > flowvisor not support the lastest Openflow version. In addition, I can't
> > try to fix this bug, because the flowvisor use your customized jar files
> > including class code.
> > 
> > Thanks and Regard Changwoo.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OPENNETWORKINGLAB/flowvisor/issues/276#issuecomment-48588210
> .

## 

김창우 | Kim, ChangWoo
KulCloud Inc.
M  82-10-4466-0103
E   changwoo.kim@kulcloud.net

**Comment by heycwkim** [comment]
It was a fixed problem I think.
