### ISSUE TITLE
make flowspace update more efficient

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#35]
Status: Open
Project:    Flowvisor
Component/s:     None
Affects Version/s:   None
Fix Version/s:  Long Term

Type:    Improvement    Priority:    Major
Reporter:   Rob Sherwood    Assignee:   Rob Sherwood
Resolution:  Unresolved Votes:   0
Labels:  gec12
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
High-level problem: Small flowspace updates are too costly when the total amount number of flowspace entries are large.
When you update the flowspace ($n$ rules, $s$ switches and $t$ slices) each of the FVSlicers (of which there are $s_t$) rebuilds its view of the flowspace, when nets in an O(n_s_t) operation. There is a relatively straight forward fix to this: instead of building t
he view up from scratch, just handle the diff (add, remove, etc.) which will reduce it to a O(d_s*t) operation, where $d$ is the size of the diff.
This should be fairly straight forward to code: embed the diff in the config update message for each FVSlicer to process and then apply the diff to their local copy of the flowspace rather than recreating the entire view from scratch.

 Comments  
Comment by Rob Sherwood [ 06/Jul/11 ]
[reposted from FLOWVISOR-98]
Rob, the only types of log events are above WARN are ALERT and CRIT in both NLR and I2, sample below:
ALERT
Jul 5 15:38:13 ofc-vm2 flowvisor: ALERT-slicer_internet2-nox-switch_ID__ofc-vm1_net_internet2_edu_29_dpid=00:00:0e:84:40:39:1b:93: STARVING: handling event took 25ms: org.flowvisor.events.FVIOEvent@4be7e13a
Jul 5 15:38:14 ofc-vm2 flowvisor: ALERT-topoDpid=00:00:0e:83:40:39:18:1b: STARVING: handling event took 110ms: org.flowvisor.events.FVIOEvent@2ac15229
Jul 5 15:38:26 ofc-vm2 flowvisor: ALERT-classifier-dpid=00:00:0e:83:40:39:18:1b: STARVING: handling event took 125ms: org.flowvisor.events.ConfigUpdateEvent@249c0dd6
Jul 5 15:38:26 ofc-vm2 flowvisor: ALERT-slicer_tupty10_ID__ofc-vm1_net_internet2_edu_21_dpid=00:00:0e:83:40:39:18:1b: STARVING: handling event took 55ms: org.flowvisor.events.FVIOEvent@5a625014
Jul 5 15:38:26 ofc-vm2 flowvisor: ALERT-slicer_tupty10_ID__ofc-vm1_net_internet2_edu_21_dpid=00:00:0e:83:40:39:1b:93: STARVING: handling event took 27ms: org.flowvisor.events.FVIOEvent@6c777f67
Jul 5 15:38:26 ofc-vm2 flowvisor: ALERT-slicer_tupty10_ID__ofc-vm1_net_internet2_edu_21_dpid=00:00:0e:83:40:39:18:58: STARVING: handling event took 26ms: org.flowvisor.events.FVIOEvent@194d7ad3
Jul 5 15:40:38 ofc-vm2 flowvisor: ALERT-slicer_fvadmin_dpid=00:00:0e:84:40:39:18:1b: STARVING: handling event took 17ms: org.flowvisor.events.FVIOEvent@4086d951
Jul 5 15:41:46 ofc-vm2 flowvisor: ALERT-classifier-dpid=00:00:0e:83:40:39:18:58: STARVING: handling event took 12ms: org.flowvisor.events.FVIOEvent@68b4f5b6
CRIT
Jul 5 15:37:18 ofc-vm2 flowvisor: CRIT-slicer_tupty10_ID__ofc-vm1_nlr_net_14_dpid=0e:83:00:23:47:ca:bc:40: FIXME: need to flush old flow entries
Jul 5 15:37:18 ofc-vm2 flowvisor: CRIT-slicer_jbs15-naxos-33015_ID__ofc-vm1_nlr_net_16_dpid=0e:83:00:23:47:ca:bc:40: FIXME: need to flush old flow entries
Jul 5 15:37:18 ofc-vm2 flowvisor: CRIT-slicer_nlr-nox-switch_ID__ofc-vm1_nlr_net_10_dpid=0e:83:00:23:47:ca:bc:40: FIXME: need to flush old flow entries

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-100

**Comment by alshabib** [comment]
This issue will be closed because it is no longer relavant to the new flowspace handling introduced in 0.8.3
