### ISSUE TITLE
Handle multiple slices in config file that have same controller

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#36]
Status: Open
Project:    Flowvisor
Component/s:    Core
Affects Version/s:  0.7.2
Fix Version/s:  Long Term

Type:    Improvement    Priority:    Minor
Reporter:   Anne Struble    Assignee:   Rob Sherwood
Resolution:  Unresolved Votes:   0
Labels:  None
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
Handle multiple slices in config file that have same controller (Branch off of flowvisor-47, which fixes this issue when encountered through rpc interface)

 Comments  
Comment by Rob Sherwood [ 03/Jun/11 ]
Just so I understand, the concern here is that while we have prevented duplicate controller URLs from ending up in the config from the RPC calls, they could still show up in the config through other means (e.g., editted by hand)?
If yes, I would say this is not a serious issue and more, this duplicate controller URL prevention was a feature to prevent users from shooting themselves in the foot, but there are certain, almost pathological situations where we might want to allow it, so hand editted config might be reasonable there.
Did I understand correctly?
Comment by Nick Bastin [ 03/Jun/11 ]
Yes, the only remaining problem is if you go behind RPC's back and configure this by hand. IMO, if users edit the config file by hand, they get what they deserve.. 
Comment by Yiannis Yiakoumis [ 12/Oct/11 ]
Just got a newer version of FV and got into this, which causes me issues. In my case the controller handles multiple (small) networks. So, I have 10 independent APs, which all go through the same FV and they end up to the same controller. But still, I want to keep them as separate slices, as they are different networks.
I use the RPC to create/delete slices dynamically, and this currently blocks me.
Thoughts??

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-91

**Comment by alshabib** [comment]
User cannot specify duplicate controllers via fvctl or API. To achieve dup controllers, they must edit the config file by hand and load it into FV and realize that they may be playing with fire.
