### ISSUE TITLE
Nightly build packages in unstable apt repo

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#37]
Status: Open
Project:    Flowvisor
Component/s:    Packaging
Affects Version/s:  0.7.2
Fix Version/s:  Next

Type:    Improvement    Priority:    Major
Reporter:   Nick Bastin Assignee:   Nick Bastin
Resolution:  Unresolved Votes:   0
Labels:  geni
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
It was proposed at the openflow bi-weekly sync that we have packages made for things that aren't releases, but so you didn't have to pull from git and build yourself. An easy manifestation of this would be to just make nightly builds in an unstable apt tree, and people could pull whatever they want, probably named something like:
flowvisor-nightly-20110530
There's probably some work that would go into making this version number work in all the right places.

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-90

**Comment by jbsbbn** [comment]
Is this covered by the new repos? The earlier https://openflow.stanford.edu/bugs/browse/FLOWVISOR-187 was closed, and I think 'unstable' has nightly builds, right?

**Comment by alshabib** [comment]
Yes the nightlies are in the unstable repo.

On 23 oct. 2012, at 18:53, Josh Smift notifications@github.com wrote:

Is this covered by the new repos? The earlier
https://openflow.stanford.edu/bugs/browse/FLOWVISOR-187 was closed, and I
think 'unstable' has nightly builds, right?

—
Reply to this email directly or view it on
GitHubhttps://github.com/OPENNETWORKINGLAB/flowvisor/issues/37#issuecomment-9709408.
