### ISSUE TITLE
If config can't be written, error should be communicated back to RPC API

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#41]
Status: Open
Project:    Flowvisor
Component/s:    RPC
Affects Version/s:  0.7.2
Fix Version/s:  Next

Type:    Improvement    Priority:    Major
Reporter:   Nick Bastin Assignee:   Ali Al-Shabibi
Resolution:  Unresolved Votes:   0
Labels:  opnk11
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
If you make an RPC call that causes the config to be written, and the config write fails (EPERM, etc.), you are not informed.

 Comments  
Comment by Josh Smift [ 28/Aug/12 ]
I created a duplicate of this ticket in FLOWVISOR-150, which was labeled "wontfix", but not actually resolved. Is this problem resolved now?
Comment by Ali Al-Shabibi [ 28/Aug/12 ]
Yes, in the new way the config is handled it is no longer written for any change (it was too much of a performance hit). Now to write the config, you must explicitely run fvctl dumpConfig <configfile>.

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-80

**Comment by alshabib** [comment]
closed as the xmlrpc interface will be deprecated in 1.0
