### ISSUE TITLE
FlowVisor 0.6.x package improvements

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#47]
Status: Open
Project:    Flowvisor
Component/s:    Packaging
Affects Version/s:  0.7.2
Fix Version/s:  Long Term

Type:    Improvement    Priority:    Major
Reporter:   Nick Bastin Assignee:   Rob Sherwood
Resolution:  Unresolved Votes:   0
Labels:  None
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
A couple of suggestions for improving the FlowVisor? 0.6.x package:
The package currently sets /usr/etc/flowvisor (and .../envs.sh) to be owned by UID 1001. Could they instead be owned by "the 'openflow' user, whatever UID that happens to have"? (Or a 'flowvisor' user, if you like that better; we currently have all our OF stuff sharing a pseudo-user, but don't feel strongly about it.)
It'd be nice if /usr/etc/flowvisor (and .../envs.sh) were world-readable.
Other Ubuntu things don't seem to use /usr/etc, so it might be more Debian-liketo use /etc/flowvisor instead of /usr/etc/flowvisor.
Could the package run 'sudo -u openflow fvconfig generateCert' after installation, but only if the cert doesn't already exist?
It'd be nice if the package was signed, so it could be installed non-interactively (e.g. via Puppet or Cfengine).

 Comments  
Comment by Josh Smift [ 28/Aug/12 ]
Most of these things have been fixed in more recent versions. For the two that haven't, I've created new, separate tickets for them: FLOWVISOR-183 for the /usr/etc -> /etc move, and FLOWVISOR-184 for the package-singing thing. I think this one can be closed.

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-43

**Comment by jbsbbn** [comment]
I'd commented, on the JIRA predecessor to this ticket, that I think these issues have been moved to other tickets, and that this one can be closed; I still think that. :^)
