### ISSUE TITLE
clean up API code

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#48]
Status: Open
Project:    Flowvisor
Component/s:    Core
Affects Version/s:  0.7.2
Fix Version/s:  Long Term

Type:    Improvement    Priority:    Major
Reporter:   Nick Bastin Assignee:   Rob Sherwood
Resolution:  Unresolved Votes:   0
Labels:  None
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
rewrite everything to use lookupSlice and lookupClassifier internal calls (code reduction)
move all API methods to synchronized and stop manually marshalling API params/responses

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-39

**Comment by alshabib** [comment]
Affects XMLRPC interface, which is now deprecated.
