### ISSUE TITLE
"fvctl changePasswd" doesn't change password

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#5]
Even though "fvctl changePasswd" shows "success!" it doesn't change password at all. This is due to a SQL syntax error in SliceImpl.java. Just changing "AND" to "," should be enough. The patch is attached.

Status: Open
Project:    Flowvisor
Component/s:    Config, Core
Affects Version/s:  0.8.3, 0.8.4, 0.8.5
Fix Version/s:   None

Type:    Bug    Priority:    Major
Reporter:   Masahiko Takahashi  Assignee:   Ali Al-Shabibi
Resolution:  Unresolved Votes:   0
Labels:  None
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

Attachments:     bugreport-changepasswd.txt    

 Description  
Even though "fvctl changePasswd" shows "success!" it doesn't change password at all. This is due to a SQL syntax error in SliceImpl.java. Just changing "AND" to "," should be enough. The patch is attached (shown below, not attached:)

diff -r e078241c2769 src/org/flowvisor/config/SliceImpl.java
--- a/src/org/flowvisor/config/SliceImpl.java   Wed Aug 08 14:41:13 2012 -0700
+++ b/src/org/flowvisor/config/SliceImpl.java   Fri Aug 10 10:56:39 2012 -0700
@@ -52,7 +52,7 @@
            " passwd_salt, controller_hostname, controller_port, contact_email, drop_policy, lldp_spam, slice_queue) " +
            "VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";
    private static String DELETESLICE = "DELETE FROM Slice WHERE " + SLICE + " = ?";
-   private static String SCRYPT = "UPDATE Slice SET " + CRYPT + " = ? AND " + SALT +
-   private static String SCRYPT = "UPDATE Slice SET " + CRYPT + " = ?, " + SALT +
          " = ? WHERE " + SLICE + " = ?";
  
  private static String FLOWVISOR = "SELECT id from " + Flowvisor.FLOWVISOR + " WHERE " + Flowvisor.CONFIG + " = ?"; 

Original issue: https://openflow.stanford.edu/bugs/si/jira.issueviews:issue-html/FLOWVISOR-181/FLOWVISOR-181.html

**Comment by jbsbbn** [comment]
This seems to have been fixed in FV 0.8.6: I was able to set the initial password at fvconfig time, and then change it with fvctl changePasswd after it was up and running ,and the password did in fact change.
