### ISSUE TITLE
make "port alread bound" fatal error clearer to the user

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#50]
Status: In Progress
Project:    Flowvisor
Component/s:    Core
Affects Version/s:  0.7.2
Fix Version/s:  Long Term

Type:    Improvement    Priority:    Major
Reporter:   Nick Bastin Assignee:   Ali Al-Shabibi
Resolution:  Unresolved Votes:   0
Labels:  None
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
If you run flowvisor and one of the ports (either OF control or XMLRPC server) is already bound, the error to the user is not very clear:
Starting FlowVisor?
--- Setting logging level to NOTE
respawning too fast -- DYING

 Comments  
Comment by Nick Bastin [ 10/Sep/11 ]
Really there are a lot of reasons that you can see "respawning too fast – DYING", we should make them all clear to the user rather than just bailing out.

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-30

**Comment by jbsbbn** [comment]
I took a look at this in FV 0.8.6, and this error has gotten better, but is still a little vague. /var/log/flowvisor/flowvisor-stderr.log says

```
--- Setting logging level to NOTE
java.net.BindException: Address already in use
    at sun.nio.ch.Net.bind(Native Method)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:137)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:77)
    at org.flowvisor.ofswitch.OFSwitchAcceptor.<init>(OFSwitchAcceptor.java:37)
    at org.flowvisor.FlowVisor.run(FlowVisor.java:161)
    at org.flowvisor.FlowVisor.main(FlowVisor.java:217)
```

but doesn't say _which_ address is in use. Could it say, perhaps something more like "Unable to listen on hostname.whatever port 6633 (address/port already in use)" or some such?

**Comment by alshabib** [comment]
fixed in nightly.
