### ISSUE TITLE
Need to be able to set a slice as "administratively down"

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#60]
Status: Open
Project:    Flowvisor
Component/s:    Core
Affects Version/s:  0.8.1
Fix Version/s:  Next

Type:    New Feature    Priority:    Major
Reporter:   Nick Bastin Assignee:   Ali Al-Shabibi
Resolution:  Unresolved Votes:   0
Labels:  willfix
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
Should be able to set a slice as administratively down, so it's not considered by the classifier (and it doesn't make controller connections, even if the controller is up).

 Comments  
Comment by Ali Al-Shabibi [ 06/Feb/12 ]
to do this cleanly, we should also remove all flow entries relevant to the given slice at the switch. This requires efficient flow tracking. See doc at https://openflow.stanford.edu/display/DOCS/Replacement+of+configuration+backend#Replacementofconfigurationbackend-FlowtrackingandRewriting and comment please.

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-132

**Comment by alshabib** [comment]
pushed to nightly. This feature also includes the ability to create a slice that is administratively down initially. See the man page for the new fvctl.
