### ISSUE TITLE
allow slice perms to be specfied with "rwd" in addition to by number

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#62]
Status: Open
Project:    Flowvisor
Component/s:     None
Affects Version/s:   None
Fix Version/s:   None

Type:    New Feature    Priority:    Minor
Reporter:   Rob Sherwood    Assignee:   Rob Sherwood
Resolution:  Unresolved Votes:   0
Labels:  None
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
from fvctl man page:
SLICEACTIONS
Slice actions is a comma separated list of slices that have control over a specific FlowSpace. Slice actions are of the form "Slice:slice‐
name1=perm[Slice:slicename2=perm[...]]". Each slice can have three types of permissions over a flowspace: DELEGATE, READ, and WRITE. Permissions
are currently a bitmask specified as an integer, with DELEGATE=1, READ=2, WRITE=4. So, "Slice:alice=5,bob=2" would give Alice's slice DELEGATE and
WRITE permissions (1+4=5), but Bob only READ permissions. Improving this interface is on the TODO list. For example,
Need to allow "r", "w", and "d" letters to make this easier to use, e.g.,
"Slice:alice=4,Slice:bob=2" becomes "Slice:alice=w,Slice:bob=r".
Should be updated both for input and for printing.

 Comments  
Comment by Josh Smift [ 27/Jun/11 ]
It would also be nice if the docs clarified that (unlike Unix file permissions) write includes read – you can't actually give someone only write privs. (If you wanted a FlowVisor slice to act like a dropbox? I have no idea why you'd want that, but the docs should make it more explicit (i.e. not just in a "for example") that you can't get it, anyway.)

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-97

**Comment by mssumanth** [comment]
Unix like support while slice creation - the 'rwd' extension.
Fixed in 1.2
Commit tag is:
6685bf82d59abf09fa1b80f23509ac8d5d7849ed
