### ISSUE TITLE
Provide RPC API as JSON service

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#65]
Status: In Progress
Project:    Flowvisor
Component/s:    RPC
Affects Version/s:  0.7.2
Fix Version/s:  Next

Type:    New Feature    Priority:    Major
Reporter:   Nick Bastin Assignee:   Anne Struble
Resolution:  Unresolved Votes:   0
Labels:  opnk11
Remaining Estimate:  0 minutes
Time Spent:  1 week
Original Estimate:   Not Specified

 Description  
The XML RPC API is really heavy and tricky to worth with in different languages as Java doesn't always serialize in the way you would expect.

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-41

**Comment by alshabib** [comment]
Pushed. Although the default is still xmlrpc. This will be changed when the release is put together.

**Comment by billsnow** [comment]
Nice work-congratulations!

Bill Snow
VP of Engineering
ON.Lab
bill@onlab.us
650.996.3164 (m)
