### ISSUE TITLE
dynamically change logging thresholds

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#72]
Status: Open
Project:    Flowvisor
Component/s:    Core
Affects Version/s:  0.7.2
Fix Version/s:  Long Term

Type:    New Feature    Priority:    Minor
Reporter:   Nick Bastin Assignee:   Rob Sherwood
Resolution:  Unresolved Votes:   0
Labels:  None
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
instead of just at boot time

 Comments  
Comment by Rob Sherwood [ 04/Jul/11 ]
This has been implemented for a while with `fvctl setConfig flowvisor!logging $LEVEL`. I had previously been mistaken thinking that more work was needed, but I'm reasonably confident this will work. Probably should add a test case to verify that this does and will always work.

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-8

**Comment by alshabib** [comment]
Currently implemented via log4j.
