### ISSUE TITLE
implement isolation for all actions, including config parameters to allow them

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#73]
Status: Open
Project:    Flowvisor
Component/s:    Core
Affects Version/s:  0.7.2
Fix Version/s:  Long Term

Type:    New Feature    Priority:    Trivial
Reporter:   Nick Bastin Assignee:   Rob Sherwood
Resolution:  Unresolved Votes:   0
Labels:  None
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Comments  
Comment by Rob Sherwood [ 04/Jul/11 ]
note: this is still an issue with current 0.7.x series of flowvisor; issolation is really only implemented for the OUTPUT action, which means that a (malicious?) slice could use, for example, a packet rewrite function, to violate slice isolation and put traffic into another slice's flowspace.
Not clear how dire this is.

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-6

**Comment by alshabib** [comment]
Issue will be split. In 0.10 we only implement all the actions.
