### ISSUE TITLE
update external dev docs with new flow id creation scheme

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#75]
Status: Open
Project:    Flowvisor
Component/s:     None
Affects Version/s:   None
Fix Version/s:   None

Type:    Task   Priority:    Minor
Reporter:   Rob Sherwood    Assignee:   Nick Bastin
Resolution:  Unresolved Votes:   0
Labels:  None
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
with flow id patch, the flow id allocation scheme is more complicated and the external dev docs need to be updated to reflect this.

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-114

**Comment by alshabib** [comment]
No longer valid because flow entry ids are not in sync with database primary key.
