### ISSUE TITLE
Create package installation user if it doesn't exist

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#9]
Status: Open
Project:    Flowvisor
Component/s:    Packaging
Affects Version/s:   None
Fix Version/s:   None

Type:    Bug    Priority:    Major
Reporter:   Josh Smift  Assignee:   Nick Bastin
Resolution:  Unresolved Votes:   0
Labels:  willfix
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
FlowVisor currently requires a 'flowvisor' user, but doesn't create that user or check for its existence. It should create a 'flowvisr' user (or other 8-character-or-less user) if one doesn't exist, and use that.

 Comments  
Comment by Josh Smift [ 14/Dec/11 ]
On further reflection, it seems like you probably shouldn't change what user FlowVisor should run as; but you still can run into the problem described here if that user doesn't exist.
Please change the description of this bug to:
FlowVisor currently requires a 'flowvisor' user, but doesn't create that user or check for its existence. It should create a 'flowvisr' user (or other 8-character-or-less user) if one doesn't exist, and use that.
Comment by Josh Smift [ 21/Sep/12 ]
On further further reflection, it's been using the username 'flowvisor' for a while now, and modern Unix is generally ok with longer-than-8-character usernames. Let's just stick with that.

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-149

**Comment by jbsbbn** [comment]
I installed FV 0.8.6-1 on a clean system just now, and confirmed that it created a 'flowvisor' user, so I think this one is all set.

**Comment by billsnow** [comment]
closing per Josh' comments
